### ISSUE TITLE
Crash in plugin when starting IntelliJ

### ISSUE THREAD

**Issue by matschaffer** [go-lang-plugin-org/go-lang-idea-plugin#1177]
Just started intellij this morning after experimenting with some golang debugging the previous night. Actually opened a puppet project not a golang project so kind of odd that I'd get a crash on the go plugin.

Additionally after hitting the "send to github" button and being prompted to fill in a full description I was unable to click the "send to github" button again. So will try to fill out as many of the automated details as I can here.

Plugin Name: Go language (golang.org) support plugin
Plugin Version: 0.9.16-dev-0.9.16-alpha.9
OS Name: Mac OS X
Java version: 1.6.0_65 (probably, I also have 1.8.0_25 installed but pretty sure IntelliJ uses 1.6)
Java vm vendor: Apple Inc. (probably)
App Name: IDEA
App Full Name: IntelliJ IDEA
App Version name: IntelliJ IDEA
Is EAP: false
App Build: IC-139.659
App Version: 14.0.2
Last Action: Not sure. Just started IntelliJ fresh this morning

```
Assertion failed
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:144)
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:153)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.initBreakpoints(XDebugSessionImpl.java:295)
	at ro.redeul.google.go.runner.GoApplicationRunner.doExecute(GoApplicationRunner.java:151)
	at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
	at com.intellij.execution.RunProfileStarter.execute(RunProfileStarter.java:39)
	at com.intellij.execution.impl.ExecutionManagerImpl$2.run(ExecutionManagerImpl.java:203)
	at com.intellij.execution.impl.ExecutionManagerImpl.compileAndRun(ExecutionManagerImpl.java:131)
	at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.java:243)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:40)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:64)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:31)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:53)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:31)
	at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:94)
	at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:375)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$400(ExecutionManagerImpl.java:60)
	at com.intellij.execution.impl.ExecutionManagerImpl$4.run(ExecutionManagerImpl.java:368)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:318)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:577)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by dlsniper** [comment]
This shouldn't happen anymore with 1.0
