### ISSUE TITLE
Can't configure Go SDK in 1.0 Alpha

### ISSUE THREAD

**Issue by mark-anders** [go-lang-plugin-org/go-lang-idea-plugin#1203]
I mentioned this on another thread.  I installed the plugin successfully, but when I attempt to configure the SDK, it correctly brings me to /usr/local/go, but when I select, nothing happens.  Here's the stack trace of the error from the log file:

2015-01-30 17:32:39,406 [  22102]  ERROR - llij.ide.plugins.PluginManager - com/goide/jps/model/JpsGoSdkType 
java.lang.NoClassDefFoundError: com/goide/jps/model/JpsGoSdkType
	at com.goide.sdk.GoSdkType.isValidSdkHome(GoSdkType.java:109)
	at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil$7.consume(SdkConfigurationUtil.java:288)
	at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil$7.consume(SdkConfigurationUtil.java:284)
	at com.intellij.ui.mac.MacFileChooserDialogImpl$3$2.run(MacFileChooserDialogImpl.java:135)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:577)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:205)
	at java.awt.Dialog$1.run(Dialog.java:1049)
	at java.awt.Dialog$3.run(Dialog.java:1101)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Dialog.show(Dialog.java:1099)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:779)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:464)
	at com.intellij.openapi.ui.DialogWrapper.showAndGetOk(DialogWrapper.java:1569)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1536)
	at com.intellij.ide.impl.NewProjectUtil.createNewProject(NewProjectUtil.java:70)
	at com.intellij.ide.actions.NewProjectAction.actionPerformed(NewProjectAction.java:31)
	at com.intellij.ui.components.labels.ActionLink$1.linkSelected(ActionLink.java:64)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:111)
	at com.intellij.ui.components.labels.ActionLink.doClick(ActionLink.java:77)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:304)
	at java.awt.Component.processMouseEvent(Component.java:6414)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
	at java.awt.Component.processEvent(Component.java:6179)
	at java.awt.Container.processEvent(Container.java:2084)
	at java.awt.Component.dispatchEventImpl(Component.java:4776)
	at java.awt.Container.dispatchEventImpl(Container.java:2142)
	at java.awt.Component.dispatchEvent(Component.java:4604)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4618)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4279)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4209)
	at java.awt.Container.dispatchEventImpl(Container.java:2128)
	at java.awt.Window.dispatchEventImpl(Window.java:2492)
	at java.awt.Component.dispatchEvent(Component.java:4604)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:717)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:690)
	at java.awt.EventQueue$3.run(EventQueue.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:573)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.ClassNotFoundException: com.goide.jps.model.JpsGoSdkType PluginClassLoader[ro.redeul.google.go, 1.0]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	... 66 more
2015-01-30 17:32:39,408 [  22104]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 14.0.3  Build #IC-139.1117.1

**Comment by SchumacherFM** [comment]
Same here with OSX and Intellij 14.0.3

**Comment by ignatov** [comment]
Please install the whole zip file.

On Saturday, January 31, 2015, Cyrill Schumacher <notifications@github.com>
wrote:

> Same here with OSX and Intellij 14.0.3
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1203#issuecomment-72301891>
> .
>


-- 
Sergey Ignatov

**Comment by ignatov** [comment]
Duplicates #1186

**Comment by SchumacherFM** [comment]
Works! Thanks!

**Comment by paxzeno** [comment]
Hey, I'm guessing that have a similar problem, which is:

java.lang.NoClassDefFoundError: com/goide/GoConstants
    at com.goide.ui.ProjectTutorialNotification.initComponent(ProjectTutorialNotification.java:49)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:568)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:610)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:245)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:125)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:359)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:116)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:87)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:504)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:486)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:170)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:64)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:362)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.goide.GoConstants PluginClassLoader[ro.redeul.google.go, 1.0]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 29 more

**Comment by dlsniper** [comment]
@paxzeno how did you installed the plugin? can you give us more details on what you did to get the error? Have you followed the instructions in the readme https://github.com/go-lang-plugin-org/go-lang-idea-plugin/#pre-release-builds on how to install the latest release?

**Comment by paxzeno** [comment]
I've opened the project on intellij, configured the intellij platform plugin sdk, then prepared plugin for deployment which created the jar, and then added the jar to the plugins and restart the intellij. Then it popped up the error I posted.

**Comment by dlsniper** [comment]
@paxzeno unfortunately that's not what you should do to get the plugin running from the sources. If you want to do so, please follow the instructions here: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/CONTRIBUTING.md#getting-started-with-the-plugin-development Basically you need to use ```Build > Build Artifacts...``` and then build the ```Go.zip``` artifact which is the one you should be installing, not the jar file.

My advice is that you should use the nightly release channel, if alpha is updating too late for you. Of course you can still compile and use the plugin from sources but this way you don't have to keep track of the changes in the repository.

**Comment by paxzeno** [comment]
@dlsniper it worked, thank you so much. :+1:
