### ISSUE TITLE
[1.0] Can't run app in 1.0 Alpha 11

### ISSUE THREAD

**Issue by mark-anders** [go-lang-plugin-org/go-lang-idea-plugin#1209]
I created a project for an existing, GOPATH based project.
I created a new launch configuration, selected Module main and set the file to:
       
           .../golang/src/ctxl/server.go

Attempting to run the app gives the following error:

           Error running Server: Cannot start process, the working directory ../golang/src/ctxl/out/production/main does not exist

**Comment by zolotov** [comment]
Please attach screenshot of created run configuration

**Comment by mark-anders** [comment]
here you go.  This is actually a different project but exibits the exact same behavior. For this, I created a simple hello world app called idea  in my gopath src folder.

![gorunconfig](https://cloud.githubusercontent.com/assets/1393014/5989383/74f34f20-a943-11e4-92d6-678a1c772d21.png)

**Comment by dlsniper** [comment]
@zolotov I experience the same issue if I run the process using the make part of the IDEA.
I get this:

```
2015-01-31 20:25:34,400 [  37565]  ERROR - nsions.impl.ExtensionPointImpl - IntelliJ IDEA 14.0.3  Build #IU-139.1117.1 
2015-01-31 20:25:34,401 [  37566]  ERROR - nsions.impl.ExtensionPointImpl - JDK: 1.8.0_31 
2015-01-31 20:25:34,401 [  37566]  ERROR - nsions.impl.ExtensionPointImpl - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-01-31 20:25:34,401 [  37566]  ERROR - nsions.impl.ExtensionPointImpl - Vendor: Oracle Corporation 
2015-01-31 20:25:34,401 [  37566]  ERROR - nsions.impl.ExtensionPointImpl - OS: Linux 
2015-01-31 20:25:35,251 [  38416]   INFO - tor.impl.FileEditorManagerImpl - Project opening took 4531 ms 
2015-01-31 20:25:36,138 [  39303]   INFO - indexing.UnindexedFilesUpdater - Indexable files iterated in 2609 ms 
2015-01-31 20:25:45,851 [  49016]   INFO - ij.compiler.impl.CompileDriver - COMPILATION STARTED (BUILD PROCESS) 
2015-01-31 20:25:46,373 [  49538]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stdout]: 20:25:46,358 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.groovy] at [jar:file:/home/florin/idea/plugins/gradle/lib/gradle.jar!/logback.groovy] 
2015-01-31 20:25:46,374 [  49539]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stdout]: 20:25:46,358 |-ERROR in ch.qos.logback.classic.LoggerContext[default] - Groovy classes are not available on the class path. ABORTING INITIALIZATION. 
2015-01-31 20:25:46,380 [  49545]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stdout]: Build process started. Classpath: /home/florin/idea/lib/jps-launcher.jar:/usr/lib/jvm/java-8-oracle/lib/tools.jar:/home/florin/idea/lib/optimizedFileManager.jar:/home/florin/idea/lib/ecj-4.4.jar 
2015-01-31 20:25:47,286 [  50451]   INFO - lij.compiler.impl.CompilerUtil - 	COMPILATION FINISHED (BUILD PROCESS); Errors: 0; warnings: 0 took 1442 ms: 0 min 1sec 
2015-01-31 20:25:47,302 [  50467]   INFO - figurations.GeneralCommandLine - Cannot start process, the working directory /home/florin/golang/src/github.com/dlsniper/backend/out/production/backend does not exist 
com.intellij.execution.ExecutionException: Cannot start process, the working directory /home/florin/golang/src/github.com/dlsniper/backend/out/production/backend does not exist
	at com.intellij.execution.configurations.GeneralCommandLine.checkWorkingDirectory(GeneralCommandLine.java:308)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:272)
	at com.goide.runconfig.GoRunningState.startProcess(GoRunningState.java:44)
	at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:80)
	at com.goide.runconfig.GoRunner.doExecute(GoRunner.java:60)
	at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
	at com.intellij.execution.RunProfileStarter.execute(RunProfileStarter.java:39)
	at com.intellij.execution.impl.ExecutionManagerImpl$2.run(ExecutionManagerImpl.java:203)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:125)
	at com.intellij.execution.impl.ExecutionManagerImpl$1$1.run(ExecutionManagerImpl.java:168)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:577)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2015-01-31 20:25:47,333 [  50498]   INFO - tion.impl.ExecutionManagerImpl - Cannot start process, the working directory /home/florin/golang/src/github.com/dlsniper/backend/out/production/backend does not exist 
com.intellij.execution.ExecutionException: Cannot start process, the working directory /home/florin/golang/src/github.com/dlsniper/backend/out/production/backend does not exist
	at com.intellij.execution.configurations.GeneralCommandLine.checkWorkingDirectory(GeneralCommandLine.java:308)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:272)
	at com.goide.runconfig.GoRunningState.startProcess(GoRunningState.java:44)
	at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:80)
	at com.goide.runconfig.GoRunner.doExecute(GoRunner.java:60)
	at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
	at com.intellij.execution.RunProfileStarter.execute(RunProfileStarter.java:39)
	at com.intellij.execution.impl.ExecutionManagerImpl$2.run(ExecutionManagerImpl.java:203)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:125)
	at com.intellij.execution.impl.ExecutionManagerImpl$1$1.run(ExecutionManagerImpl.java:168)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:577)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2015-01-31 20:25:47,639 [  50804]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stdout]: 20:25:47,627 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.groovy] at [jar:file:/home/florin/idea/plugins/gradle/lib/gradle.jar!/logback.groovy] 
2015-01-31 20:25:47,639 [  50804]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stdout]: 20:25:47,628 |-ERROR in ch.qos.logback.classic.LoggerContext[default] - Groovy classes are not available on the class path. ABORTING INITIALIZATION. 
2015-01-31 20:25:47,650 [  50815]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stdout]: Build process started. Classpath: /home/florin/idea/lib/jps-launcher.jar:/usr/lib/jvm/java-8-oracle/lib/tools.jar:/home/florin/idea/lib/optimizedFileManager.jar:/home/florin/idea/lib/ecj-4.4.jar 
```

Please have a look at the build / run options we have in 0.9.16 as they contain everything a go user might need.

**Comment by IAmYmir** [comment]
Error:Failed to launch go compiler: Cannot start process, the working directory C:\software\develop\intelijidea\workspace\golang does not exist

**Comment by dlsniper** [comment]
@IAmYmir what version of the plugin are you using? what's your setup? what are you trying to do specifically? Also have you seen that in the latest release we do mention that the plugin support for running apps/tests is still lacking? Please help us help you :)

**Comment by IAmYmir** [comment]
Error:Failed to launch go compiler: Cannot start process, the working directory C:\software\develop\intelijidea\workspace\golang does not exist
image
image

**Comment by dlsniper** [comment]
@IAmYmir please read this article on how to report errors: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/contributing.md#reporting-errors
