### ISSUE TITLE
Imports vs injections

### ISSUE THREAD

**Issue by ignatov** [go-lang-plugin-org/go-lang-idea-plugin#1325]
Please inject Go lang into those two strings and Voilà!

```go
package main
import "fmt"
func main() {
    fmt.Println(`package a;
    import "fmt"
    func main() { fmt.Println()}`)

    fmt.Println("package a; \nimport \"fmt\"; \nfunc main() { fmt.Println()}\n\n\nfunc foo() {\n    fmt.Println(\"hello\")\n}")
}
```

**Comment by dlsniper** [comment]
As of e5b85cf4fef9fe6b22c8721c4bb0b764bd2ebae6 injecting into the first string works ok but into the double quotes one it messes things up really bad.

**Comment by dlsniper** [comment]
A small update for this one. If I use the `Inject language or reference` feature on the fmt.Println() line then the plugin seems to enter in sort of an infinite loop while testing with 0.10.609.

I also get this trace in the log file and it keeps repeating for quite a while:

```
2015-11-03 23:54:03,758 [  36339]  ERROR - aemon.impl.PassExecutorService - String index out of range: 7 
java.lang.StringIndexOutOfBoundsException: String index out of range: 7
	at java.lang.String.charAt(String.java:658)
	at com.goide.psi.impl.GoPsiImplUtil.getPath(GoPsiImplUtil.java:963)
	at com.goide.psi.impl.GoImportStringImpl.getPath(GoImportStringImpl.java:51)
	at com.goide.psi.impl.GoPsiImplUtil.getPath(GoPsiImplUtil.java:920)
	at com.goide.psi.impl.GoImportSpecImpl.getPath(GoImportSpecImpl.java:86)
	at com.goide.psi.impl.GoPsiImplUtil.isCImport(GoPsiImplUtil.java:909)
	at com.goide.psi.impl.GoImportSpecImpl.isCImport(GoImportSpecImpl.java:95)
	at com.goide.psi.GoFile.hasCPathImport(GoFile.java:436)
	at com.goide.util.GoBuildMatcher.matchFile(GoBuildMatcher.java:56)
	at com.goide.util.GoBuildMatcher.matchFile(GoBuildMatcher.java:45)
	at com.goide.util.GoUtil.allowed(GoUtil.java:73)
	at com.goide.inspections.GoInspectionBase.buildVisitor(GoInspectionBase.java:36)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:60)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:709)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$1200(LocalInspectionsPass.java:73)

[...]
2015-11-03 23:54:03,763 [  36344]  ERROR - aemon.impl.PassExecutorService - IntelliJ IDEA 15.0  Build #IU-143.381.42 
2015-11-03 23:54:03,763 [  36344]  ERROR - aemon.impl.PassExecutorService - JDK: 1.8.0_66 
2015-11-03 23:54:03,763 [  36344]  ERROR - aemon.impl.PassExecutorService - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-11-03 23:54:03,763 [  36344]  ERROR - aemon.impl.PassExecutorService - Vendor: Oracle Corporation 
2015-11-03 23:54:03,763 [  36344]  ERROR - aemon.impl.PassExecutorService - OS: Linux 
2015-11-03 23:54:03,764 [  36345]  ERROR - aemon.impl.PassExecutorService - Last Action: ShowIntentionActions
```
