### ISSUE TITLE
NullPointerException with unclear reason

### ISSUE THREAD

**Issue by bong0** [go-lang-plugin-org/go-lang-idea-plugin#1345]
Got this exception today while editing. I saw it in the console when It had occured ten minutes before. I was only editing pretty much. I did not even build my project at that time.

```null
java.lang.NullPointerException
	at ro.redeul.google.go.lang.psi.impl.expressions.primary.GoSelectorExpressionImpl.getReferences(GoSelectorExpressionImpl.java:160)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.a(SharedPsiElementImplUtil.java:67)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:49)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:63)
	at com.intellij.psi.impl.PsiElementBase.findReferenceAt(PsiElementBase.java:87)
	at com.intellij.psi.SingleRootFileViewProvider.a(SingleRootFileViewProvider.java:415)
	at com.intellij.psi.SingleRootFileViewProvider.findReferenceAt(SingleRootFileViewProvider.java:387)
	at com.intellij.psi.impl.source.PsiFileImpl.findReferenceAt(PsiFileImpl.java:613)
	at com.intellij.codeInsight.TargetElementUtilBase.findReference(TargetElementUtilBase.java:116)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferenceOrReferencedElement(TargetElementUtilBase.java:304)
	at com.intellij.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:95)
	at com.intellij.codeInsight.TargetElementUtilBase.findTargetElement(TargetElementUtilBase.java:200)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:60)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:88)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1146)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:281)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

OS: Fedora 21 with latest upgrades
JRE: openjdk version "1.8.0_31"
IDEA: 14.0.3 regular stable relase (latest)
Plugin: 0.9.15.3
Go: go version go1.3.3 linux/amd64

**Comment by dlsniper** [comment]
Hi @bong0.

Please give us more details about the problem you have:
- what plugin version are you using (or commit hash if you compiled the plugin yourself)
- what version of IDEA you have 
- what version of Go / OS you have

Any way to replicate the issue would be also very helpful.

Thank you.

**Comment by bong0** [comment]
@dlsniper I updated the issue just now

**Comment by dlsniper** [comment]
@bong0 Thanks. Please use the latest release from here: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/releases and things should be solved. We can't release it just yet but things should be much more stable and it has a completely reworked internal engine.

I'll close this for now but feel free to either open it again or to open new issues if needed. Any PRs are also gladly welcomed. :)
