### ISSUE TITLE
Plugin doesn't recognize GoSDK

### ISSUE THREAD

**Issue by olegdunkan** [go-lang-plugin-org/go-lang-idea-plugin#1419]
IDE: Intelij IDE 14.0.3 
OS: Windows 8.1
Golang version: 1.4
GOROOT: D:\Go
GOPATH: not important 

Installed folder structure: 

D:\Go\pkg\windows_amd64\... (packages)
D:\Go\src\... (package sources)
D:\Go\bin\

For GoSDK folder I select D:\Go but it doesn't work 
I have tried  
D:\Go\pkg\windows_amd64\
D:\Go\pkg\
D:\Go\src

but no one isn't eaten by plugin I think your plugin is not hungry, what's wrong I did?  
Thanks a lot!

**Comment by dlsniper** [comment]
What version of the plugin are you using? if it's 0.9.16 or earlier please use the latest version from the github releases section. If not please reopen this issue. Thank you.

**Comment by olegdunkan** [comment]
I used 0.9.164 version

**Comment by olegdunkan** [comment]
I have checked logs and that's what I saw 
a bunch of error like a - 
 
2015-03-09 14:38:46,803 [  39212]  ERROR - aemon.impl.PassExecutorService - IntelliJ IDEA 14.0.3  Build #IU-139.1117.1 
2015-03-09 14:38:46,804 [  39213]  ERROR - aemon.impl.PassExecutorService - JDK: 1.8.0_25 
2015-03-09 14:38:46,804 [  39213]  ERROR - aemon.impl.PassExecutorService - VM: Java HotSpot(TM) Server VM 
2015-03-09 14:38:46,805 [  39214]  ERROR - aemon.impl.PassExecutorService - Vendor: Oracle Corporation 
2015-03-09 14:38:46,806 [  39215]  ERROR - aemon.impl.PassExecutorService - OS: Windows 8 
2015-03-09 14:38:46,806 [  39215]  ERROR - aemon.impl.PassExecutorService - Last Action: ShowProjectStructureSettings 
2015-03-09 14:38:46,806 [  39215]  ERROR - aemon.impl.PassExecutorService - com/goide/GoEnvironmentUtil 
java.lang.NoClassDefFoundError: com/goide/GoEnvironmentUtil
	at com.goide.sdk.GoSdkUtil.getGoPathsSourcesFromEnvironment(GoSdkUtil.java:116)
	at com.goide.sdk.GoSdkUtil.getGoPathsSources(GoSdkUtil.java:92)
	at com.goide.sdk.GoSdkUtil.getGoPathsSources(GoSdkUtil.java:87)
	at com.goide.psi.impl.imports.GoImportReferenceHelper.getPathsToLookup(GoImportReferenceHelper.java:103)
	at com.goide.psi.impl.imports.GoImportReferenceHelper.getContexts(GoImportReferenceHelper.java:85)
	at com.goide.psi.impl.imports.GoFileContextProvider.getContextFolders(GoFileContextProvider.java:40)

**Comment by zolotov** [comment]
From release description:
```
You need to install the zip file, do not extract its contents. For more information, check the README
```

**Comment by zolotov** [comment]
And from README:
```
Note for Mac OS X users: you need to download the entire zip file, not a several jars (see Apple discussion forum).
```

**Comment by olegdunkan** [comment]
Oooo mama mia, it is works. If i see something zipped my first intention is to extract it and then apply.
Sometimes habits do wrong things) Maybe it is possible to make some checks against this happen while installing plugin?
Thanks a lot!

**Comment by zolotov** [comment]
It's too hard to do it and it won't be needed after we'll publish the plugin in jetbrains repository.

**Comment by olegdunkan** [comment]
Yes, I agree with you, your are right! Спасибо Саша!
