### ISSUE TITLE
CNFE Error editing yaml files

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1536]
I'm editing a project with a yaml file and a Go SDK attached and I've got this error while typing  something into the file:

```
java.lang.ClassNotFoundException: yaml.AppEngineYamlCompletionContributor PluginClassLoader[ro.redeul.google.go, 1.0]
java.lang.RuntimeException: java.lang.ClassNotFoundException: yaml.AppEngineYamlCompletionContributor PluginClassLoader[ro.redeul.google.go, 1.0]
	at com.intellij.lang.LanguageExtensionPoint$1.compute(LanguageExtensionPoint.java:45)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:39)
	at com.intellij.lang.LanguageExtensionPoint.getInstance(LanguageExtensionPoint.java:53)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:154)
	at com.intellij.codeInsight.completion.CompletionContributor$MyExtensionPointManager.buildExtensions(CompletionContributor.java:266)
	at com.intellij.codeInsight.completion.CompletionContributor$MyExtensionPointManager.buildExtensions(CompletionContributor.java:250)
	at com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:115)
```

Plugin hash: 7192e5a7a1a0824dfea50fba66efa8665dee19a0

file.yaml
```yml
type<caret> #IDE should have failed by now
```

Please let me know if you need more details.

**Comment by dlsniper** [comment]
Thank you!
