### ISSUE TITLE
Cannot cast bash file to go file

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1542]
I have the bash support plugin installed.
While editing a .sh file I've right clicked on the file and this happened

As it doesn't seem too hard / long to do I'll fix it myself.
```
update failed for AnAction with ID=CreateRunConfiguration: com.ansorgit.plugins.bash.lang.psi.impl.BashFileImpl cannot be cast to com.goide.psi.GoFile
java.lang.ClassCastException: com.ansorgit.plugins.bash.lang.psi.impl.BashFileImpl cannot be cast to com.goide.psi.GoFile
	at com.goide.runconfig.testing.GoTestRunConfigurationProducer.isConfigurationFromContext(GoTestRunConfigurationProducer.java:117)
	at com.goide.runconfig.testing.GoTestRunConfigurationProducer.isConfigurationFromContext(GoTestRunConfigurationProducer.java:38)
	at com.intellij.execution.actions.RunConfigurationProducer.findExistingConfiguration(RunConfigurationProducer.java:178)
	at com.intellij.execution.actions.ConfigurationContext.findExisting(ConfigurationContext.java:200)
	at com.intellij.execution.actions.BaseRunConfigurationAction.update(BaseRunConfigurationAction.java:191)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:114)
	at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:188)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:139)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:164)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:164)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:164)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:86)
```

**Comment by zolotov** [comment]
Sure, use `PsiFile file = contextElement.getContainingFile(); if (GoTestFinder.isTestFile(file)) { }` for that. Just like in `setupConfigurationFromContext` method
