### ISSUE TITLE
Stub and PSI element type mismatch (again)

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1567]
Hi,

I've got two of these today by doing the following steps:
- open three different Go project in tree IDE windows
- disabled the ```.ignore``` (version 1.1.1) plugin
- selected to restart the IDE after disabling the ```.ignore``` plugin
- I've waited for IDEA to finish indexing the before doing anything else

I was jumping between windows, both IDE and other apps, while the indexing was happening and a bit after.

Plugin version: e5e95be18a4b8029ce4fb5594a958824869bd43f

Log:

```
2015-04-21 14:15:05,929 [  89741]  ERROR - aemon.impl.PassExecutorService - Stub and PSI element type mismatch in server.go: stub GoTypeStub, AST PAR_TYPE; Element(PAR_TYPE)
 file=GO_FILE, modStamp=0
 stub debugInfo=created in getStubTree(); with backReference
 document before=null
latestIndexedStub=com.intellij.psi.stubs.StubTree@7a5889c8
   same size=true
   debugInfo=created from index; with backReference
 viewProvider=SingleRootFileViewProvider{myVirtualFile=file:///usr/local/go/src/net/http/server.go, content=DocumentContent{size=61559}}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1424234349000; file length: 61559
 doc saved: true; doc stamp: 0; doc size: 61559; committed: true
indexing info: indexed at 1424234349000 with size 61559
------------
 
java.lang.AssertionError: Stub and PSI element type mismatch in server.go: stub GoTypeStub, AST PAR_TYPE; Element(PAR_TYPE)
 file=GO_FILE, modStamp=0
 stub debugInfo=created in getStubTree(); with backReference
 document before=null
latestIndexedStub=com.intellij.psi.stubs.StubTree@7a5889c8
   same size=true
   debugInfo=created from index; with backReference
 viewProvider=SingleRootFileViewProvider{myVirtualFile=file:///usr/local/go/src/net/http/server.go, content=DocumentContent{size=61559}}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1424234349000; file length: 61559
 doc saved: true; doc stamp: 0; doc size: 61559; committed: true
indexing info: indexed at 1424234349000 with size 61559
------------

	at com.intellij.psi.impl.source.PsiFileImpl.reportStubAstMismatch(PsiFileImpl.java:339)
	at com.intellij.psi.impl.source.PsiFileImpl$1.visitNode(PsiFileImpl.java:274)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitComposite(RecursiveTreeElementWalkingVisitor.java:80)
	at com.intellij.psi.impl.source.tree.CompositeElement.acceptTree(CompositeElement.java:158)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor$1.visit(RecursiveTreeElementWalkingVisitor.java:66)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor$1.visit(RecursiveTreeElementWalkingVisitor.java:58)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitNode(RecursiveTreeElementWalkingVisitor.java:85)
	at com.intellij.psi.impl.source.PsiFileImpl$1.visitNode(PsiFileImpl.java:283)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitComposite(RecursiveTreeElementWalkingVisitor.java:80)
	at com.intellij.psi.impl.source.tree.CompositeElement.acceptTree(CompositeElement.java:158)
	at com.intellij.psi.impl.source.PsiFileImpl.a(PsiFileImpl.java:257)
	at com.intellij.psi.impl.source.PsiFileImpl.b(PsiFileImpl.java:187)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:758)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:88)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.findChildByType(ASTDelegatePsiElement.java:180)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.findNotNullChildByType(ASTDelegatePsiElement.java:199)
	at com.goide.psi.impl.GoTypeSpecImpl.getIdentifier(GoTypeSpecImpl.java:40)
	at com.goide.psi.impl.GoPsiImplUtil.calcMethods(GoPsiImplUtil.java:617)
	at com.goide.psi.impl.GoPsiImplUtil.access$000(GoPsiImplUtil.java:61)
	at com.goide.psi.impl.GoPsiImplUtil$6.compute(GoPsiImplUtil.java:608)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:131)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:200)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:83)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:127)
	at com.goide.psi.impl.GoPsiImplUtil.getMethods(GoPsiImplUtil.java:604)
	at com.goide.psi.impl.GoTypeSpecImpl.getMethods(GoTypeSpecImpl.java:50)
	at com.goide.psi.impl.GoReference.processExistingType(GoReference.java:224)
	at com.goide.psi.impl.GoReference.processGoType(GoReference.java:191)
	at com.goide.psi.impl.GoReference.processInTypeRef(GoReference.java:275)
	at com.goide.psi.impl.GoReference.processTypeRef(GoReference.java:209)
	at com.goide.psi.impl.GoReference.processGoType(GoReference.java:200)
	at com.goide.psi.impl.GoReference.processSelector(GoReference.java:395)
	at com.goide.psi.impl.GoReference.processUnqualifiedResolve(GoReference.java:330)
	at com.goide.psi.impl.GoReference.processResolveVariants(GoReference.java:169)
	at com.goide.psi.impl.GoReference.resolveInner(GoReference.java:74)
	at com.goide.psi.impl.GoReference.access$000(GoReference.java:50)
	at com.goide.psi.impl.GoReference$1.resolve(GoReference.java:62)
	at com.goide.psi.impl.GoReference$1.resolve(GoReference.java:58)
	at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:139)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
	at com.goide.psi.impl.GoReference.multiResolve(GoReference.java:150)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:46)
	at com.goide.GoAnnotator.annotate(GoAnnotator.java:49)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:159)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:340)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$100(GeneralHighlightingPass.java:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$3.run(GeneralHighlightingPass.java:269)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:294)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:300)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:266)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:205)
 //// REMOVED
2015-04-21 14:15:05,934 [  89746]  ERROR - aemon.impl.PassExecutorService - IntelliJ IDEA (Cassiopeia) IU-141.712.1  Build #IU-141.712.1 
2015-04-21 14:15:05,934 [  89746]  ERROR - aemon.impl.PassExecutorService - JDK: 1.8.0_45 
2015-04-21 14:15:05,934 [  89746]  ERROR - aemon.impl.PassExecutorService - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-04-21 14:15:05,934 [  89746]  ERROR - aemon.impl.PassExecutorService - Vendor: Oracle Corporation 
2015-04-21 14:15:05,935 [  89747]  ERROR - aemon.impl.PassExecutorService - OS: Linux 
```

Full log + thread dumps: https://www.dropbox.com/s/gimygydtxyx3mk0/stub%20and%20psi.tar.gz?dl=0

**Comment by dlsniper** [comment]
I've forgot to mention, I've restarted the IDE with clear cache option and only one project window before restarting and then the error didn't happened again, all looks ok now.

**Comment by ignatov** [comment]
@dlsniper Please specify your go sdk version.

**Comment by dlsniper** [comment]
1.4.2 for Linux, installed from the tar.gz archive on the website. I get these from time to time, I'm not really sure how to best reproduce them in a consistent manner

**Comment by ignatov** [comment]
go1.4.2.linux-amd64.tar.gz?

**Comment by dlsniper** [comment]
Yes, that's the one. https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz
