### ISSUE TITLE
Settings cannot be opened

### ISSUE THREAD

**Issue by kokizzu** [go-lang-plugin-org/go-lang-idea-plugin#1646]
Using latest revision 058a61d84fc4b66872b2b5e020c1cdb4a1c5520c
JDK: 8.0 Linux 64-bit
when opening File > Settings, this log shows up:

```
[  57890]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 14.1.3  Build #IU-141.1010.3 
[  57890]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_45 
[  57890]  ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK 64-Bit Server VM 
[  57890]  ERROR - llij.ide.plugins.PluginManager - Vendor: Oracle Corporation 
[  57890]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
[  57890]  ERROR - llij.ide.plugins.PluginManager - Last Action: ShowSettings 

[ 117678]   WARN - options.ex.ConfigurableWrapper - XML does not provide id for class org.jetbrains.sbt.settings.SbtExternalSystemConfigurable 
[ 117679]  ERROR - llij.ide.plugins.PluginManager - null 
java.lang.NullPointerException
        at com.goide.configuration.GoBuildTargetConfigurable.<init>(GoBuildTargetConfigurable.java:74)
        at com.goide.configuration.GoConfigurableProvider.createConfigurable(GoConfigurableProvider.java:40)
        at com.intellij.openapi.options.ConfigurableEP$ProviderProducer.createElement(ConfigurableEP.java:220)
        at com.intellij.openapi.options.ConfigurableEP.createConfigurable(ConfigurableEP.java:167)
        at com.intellij.openapi.options.ex.ConfigurableWrapper.getConfigurable(ConfigurableWrapper.java:111)
        at com.intellij.openapi.options.ex.ConfigurableWrapper.cast(ConfigurableWrapper.java:94)
        at com.intellij.openapi.options.ex.ConfigurableWrapper.getId(ConfigurableWrapper.java:192)
        at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.buildConfigurablesList(ConfigurableExtensionPointUtil.java:58)
        at com.intellij.openapi.options.ex.ConfigurablesGroupBase.getConfigurables(ConfigurablesGroupBase.java:49)
        at com.intellij.ide.actions.ShowSettingsUtilImpl.a(ShowSettingsUtilImpl.java:98)
        at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurableGroups(ShowSettingsUtilImpl.java:83)
        at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:65)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:312)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
        at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
        at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:512)
        at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
        at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
        at java.awt.Component.processMouseEvent(Component.java:6525)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6290)
        at java.awt.Container.processEvent(Container.java:2234)
        at java.awt.Component.dispatchEventImpl(Component.java:4881)
        at java.awt.Container.dispatchEventImpl(Container.java:2292)
        at java.awt.Component.dispatchEvent(Component.java:4703)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
        at java.awt.Container.dispatchEventImpl(Container.java:2278)
        at java.awt.Window.dispatchEventImpl(Window.java:2750)
        at java.awt.Component.dispatchEvent(Component.java:4703)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
[ 117680]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 14.1.3  Build #IU-141.1010.3 
[ 117680]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_45 
[ 117680]  ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK 64-Bit Server VM 
[ 117680]  ERROR - llij.ide.plugins.PluginManager - Vendor: Oracle Corporation 
[ 117680]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
[ 117680]  ERROR - llij.ide.plugins.PluginManager - Last Action: ShowSettings 
```

and no Settings dialog shown

**Comment by ignatov** [comment]
Please enable UI Designer plugin and rebuild the project.

**Comment by kokizzu** [comment]
ok, it works fine now

**Comment by kokizzu** [comment]
It happened again, even when UI Designer enabled while building.

this only happened when go plugin installed, 
The settings can be opened when no projects opened (on project selection menu)

```
[  26542]   WARN - options.ex.ConfigurableWrapper - XML does not provide id for class com.goide.configuration.GoConfigurableProvider$GoCompositeConfigurable 
[  26818]  ERROR - e.actions.ShowSettingsUtilImpl - Can't find bundle for base name com.intellij.plugins.watcher.BackgroundTaskBundle, locale en_US 
java.util.MissingResourceException: Can't find bundle for base name com.intellij.plugins.watcher.BackgroundTaskBundle, locale en_US
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:1082)
        at com.intellij.AbstractBundle.getResourceBundle(AbstractBundle.java:91)
        at com.intellij.openapi.options.ConfigurableEP.getDisplayName(ConfigurableEP.java:55)
        at com.intellij.openapi.options.ex.ConfigurableWrapper.getDisplayName(ConfigurableWrapper.java:141)
        at com.intellij.openapi.options.newEditor.SettingsTreeView$MyNode.<init>(SettingsTreeView.java:456)
        at com.intellij.openapi.options.newEditor.SettingsTreeView$MyNode.buildChildren(SettingsTreeView.java:475)
        at com.intellij.ui.treeStructure.CachingSimpleNode.getChildren(CachingSimpleNode.java:36)
        at com.intellij.ui.treeStructure.SimpleTreeStructure.getChildElements(SimpleTreeStructure.java:25)
        at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.addToCache(FilteringTreeStructure.java:67)
        at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.addToCache(FilteringTreeStructure.java:82)
        at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.rebuild(FilteringTreeStructure.java:62)
        at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.<init>(FilteringTreeStructure.java:54)
        at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.<init>(FilteringTreeStructure.java:45)
        at com.intellij.ui.treeStructure.filtered.FilteringTreeBuilder.<init>(FilteringTreeBuilder.java:52)
        at com.intellij.openapi.options.newEditor.SettingsTreeView$MyBuilder.<init>(SettingsTreeView.java:776)
        at com.intellij.openapi.options.newEditor.SettingsTreeView.<init>(SettingsTreeView.java:202)
        at com.intellij.openapi.options.newEditor.SettingsEditor.<init>(SettingsEditor.java:143)
        at com.intellij.openapi.options.newEditor.SettingsDialog.<init>(SettingsDialog.java:66)
        at com.intellij.ide.actions.ShowSettingsUtilImpl.getDialog(ShowSettingsUtilImpl.java:63)
        at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:114)
        at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:65)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:312)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
        at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
        at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:512)
        at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
        at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
        at java.awt.Component.processMouseEvent(Component.java:6525)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6290)
        at java.awt.Container.processEvent(Container.java:2234)
        at java.awt.Component.dispatchEventImpl(Component.java:4881)
        at java.awt.Container.dispatchEventImpl(Container.java:2292)
        at java.awt.Component.dispatchEvent(Component.java:4703)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
        at java.awt.Container.dispatchEventImpl(Container.java:2278)
        at java.awt.Window.dispatchEventImpl(Window.java:2750)
        at java.awt.Component.dispatchEvent(Component.java:4703)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassCastException: com.intellij.plugins.watcher.BackgroundTaskBundle cannot be cast to ResourceBundle
        at java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:2647)
        at java.util.ResourceBundle.loadBundle(ResourceBundle.java:1501)
        at java.util.ResourceBundle.findBundle(ResourceBundle.java:1465)
        at java.util.ResourceBundle.findBundle(ResourceBundle.java:1419)
        at java.util.ResourceBundle.findBundle(ResourceBundle.java:1419)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1361)
        ... 65 more
[  26819]  ERROR - e.actions.ShowSettingsUtilImpl - IntelliJ IDEA 14.1.3  Build #IU-141.1010.3 
[  26819]  ERROR - e.actions.ShowSettingsUtilImpl - JDK: 1.8.0_45 
[  26819]  ERROR - e.actions.ShowSettingsUtilImpl - VM: OpenJDK 64-Bit Server VM 
[  26819]  ERROR - e.actions.ShowSettingsUtilImpl - Vendor: Oracle Corporation 
[  26819]  ERROR - e.actions.ShowSettingsUtilImpl - OS: Linux 
[  26820]  ERROR - e.actions.ShowSettingsUtilImpl - Last Action: ShowSettings 
```

**Comment by zolotov** [comment]
It's not  `again`, this is completely different exception and it has nothing to do with Go plugin.

**Comment by kokizzu** [comment]
youre right, my bad..
