### ISSUE TITLE
NPE in GoBuildTargetConfigurable.java

### ISSUE THREAD

**Issue by agitelman** [go-lang-plugin-org/go-lang-idea-plugin#1660]
I am getting this exception. It appears that UI components are not initialized. Problem only occurred on Ubuntu 12 but not on Macos.
I temporary fixed it my initializing those UI components with default constructors.

```
[ 613776]  ERROR - llij.ide.plugins.PluginManager - null 
java.lang.NullPointerException
	at com.goide.configuration.GoBuildTargetConfigurable.<init>(GoBuildTargetConfigurable.java:74)
	at com.goide.configuration.GoConfigurableProvider.createConfigurable(GoConfigurableProvider.java:40)
	at com.intellij.openapi.options.ConfigurableEP$ProviderProducer.createElement(ConfigurableEP.java:220)
	at com.intellij.openapi.options.ConfigurableEP.createConfigurable(ConfigurableEP.java:167)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getConfigurable(ConfigurableWrapper.java:111)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.cast(ConfigurableWrapper.java:94)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getId(ConfigurableWrapper.java:192)
	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.buildConfigurablesList(ConfigurableExtensionPointUtil.java:58)
	at com.intellij.openapi.options.ex.ConfigurablesGroupBase.getConfigurables(ConfigurablesGroupBase.java:49)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.a(ShowSettingsUtilImpl.java:98)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurableGroups(ShowSettingsUtilImpl.java:83)
	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:65)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:162)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:126)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:303)
	at java.awt.Component.processEvent(Component.java:6292)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4883)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4705)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4705)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
[ 613778]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA (Cassiopeia) IU-141.1192.2  Build #IU-141.1192.2 
[ 613778]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_11 
[ 613778]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM 
[ 613778]  ERROR - llij.ide.plugins.PluginManager - Vendor: Oracle Corporation 
[ 613778]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
[ 613778]  ERROR - llij.ide.plugins.PluginManager - Last Action: ShowSettings 
```

**Comment by dlsniper** [comment]
Hi, please enable the UI Designer plugin when building the plugin from the source. If you are not building it from the sources, please specify the plugin version.

For more details on how to build the plugin from the source, please see https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/CONTRIBUTING.md#getting-started-with-the-plugin-development

For how to install the plugin from the official alpha / nightly builds: https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds

Thank you

**Comment by agitelman** [comment]
Yes. That worked. Thanks.
Is there a way to fail build in case UI Designer is not doing it's work?

**Comment by dlsniper** [comment]
@ignatov seems people don't read the contributing file for this plugin as opposed to the Erlang one :d (as a reference https://github.com/go-lang-plugin-org/go-lang-idea-plugin/commit/6bfeb3b56018faae38080d5b014f6a426f1d0051#commitcomment-11369839 ). :)
