### ISSUE TITLE
about install go plugin after, can open setting panel

### ISSUE THREAD

**Issue by wuchuguang** [go-lang-plugin-org/go-lang-idea-plugin#1679]
i use intellijIDEA 14.1.3 (Linux Redhat Version)
install go plugin 
cant open setting(Ctrl+Alt+S) panel

![qq 20150610162614](https://cloud.githubusercontent.com/assets/1677247/8078119/cf2cac38-0f8d-11e5-8dab-8857b07b4890.png)
click setting , but cant open setting panel

when i delete GoPlugin (/.IntellijIdea14/config/plugins/Go/)  , Normal again
i am a chinese

**Comment by wuchuguang** [comment]
i install Go.zip this zip file (compile this plugin ,i use java1.8.46 version)

**Comment by dlsniper** [comment]
Please see this link: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/CONTRIBUTING.md#getting-started-with-the-plugin-development on how to compile the plugin yourself. Or just follow the instructions from the readme and use the nightly channel: https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds

**Comment by wuchuguang** [comment]
when i click setting menu button
 ERROR - llij.ide.plugins.PluginManager - null 
java.lang.NullPointerException
	at com.goide.configuration.GoBuildTargetConfigurable.<init>(GoBuildTargetConfigurable.java:79)
	at com.goide.configuration.GoConfigurableProvider.createConfigurable(GoConfigurableProvider.java:40)
	at com.intellij.openapi.options.ConfigurableEP$ProviderProducer.createElement(ConfigurableEP.java:220)
	at com.intellij.openapi.options.ConfigurableEP.createConfigurable(ConfigurableEP.java:167)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getConfigurable(ConfigurableWrapper.java:111)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.cast(ConfigurableWrapper.java:94)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getId(ConfigurableWrapper.java:192)
	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.buildConfigurablesList(ConfigurableExtensionPointUtil.java:58)
	at com.intellij.openapi.options.ex.ConfigurablesGroupBase.getConfigurables(ConfigurablesGroupBase.java:49)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.a(ShowSettingsUtilImpl.java:98)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurableGroups(ShowSettingsUtilImpl.java:83)
	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:65)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:312)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:512)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
[  76022]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 14.1.3  Build #IU-141.1010.3 
[  76022]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_45 
[  76022]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM 
[  76022]  ERROR - llij.ide.plugins.PluginManager - Vendor: Oracle Corporation 
[  76022]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
[  76023]  ERROR - llij.ide.plugins.PluginManager - Last Action: ShowSettings

**Comment by ignatov** [comment]
If you've created your application from sources please enable `UI Designer` plugin.

**Comment by wuchuguang** [comment]
thanks , i use https://plugins.jetbrains.com/plugins/nightly/5047  
success
