### ISSUE TITLE
v0.9.346: NoClassDefFoundError: freemarker/template/utility/StringUtil

### ISSUE THREAD

**Issue by angelow1337** [go-lang-plugin-org/go-lang-idea-plugin#1681]
Causes a broken inspection. 
Occurs when the following code was written (i think its caused by "for i, rune := range actionName"):
``` go
actionName := "test"
for i, rune := range actionName {
	fmt.Println(i)
	fmt.Println(rune)
}
```

Stacktrace:

freemarker/template/utility/StringUtil
java.lang.NoClassDefFoundError: freemarker/template/utility/StringUtil
	at com.goide.inspections.GoReservedWordUsedAsName.registerProblem(GoReservedWordUsedAsName.java:85)
	at com.goide.inspections.GoReservedWordUsedAsName.check(GoReservedWordUsedAsName.java:71)
	at com.goide.inspections.GoReservedWordUsedAsName.access$100(GoReservedWordUsedAsName.java:30)
	at com.goide.inspections.GoReservedWordUsedAsName$1.visitVarDefinition(GoReservedWordUsedAsName.java:42)
	at com.goide.psi.impl.GoVarDefinitionImpl.accept(GoVarDefinitionImpl.java:28)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:80)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:285)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$200(LocalInspectionsPass.java:75)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:254)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:251)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

**Comment by dlsniper** [comment]
Hi, which IDE, version and name, are you using? And sorry, I guess I'm the one who broke it :-D
