### ISSUE TITLE
NoSuchMethodError when using the plugin compiled against IDEA 15 EAP on IDEA 14 IC

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1709]
Hi,

I'm not sure if this intended or not, here's the log that I have.

```
2015-06-28 12:53:52,767 [  53276]  ERROR - llij.ide.plugins.PluginManager - com.intellij.ui.CollectionListModel: method <init>()V not found 
java.lang.NoSuchMethodError: com.intellij.ui.CollectionListModel: method <init>()V not found
	at com.goide.configuration.GoLibrariesConfigurable.<init>(GoLibrariesConfigurable.java:55)
	at com.goide.configuration.GoLibrariesConfigurableProvider$1.createConfigurables(GoLibrariesConfigurableProvider.java:119)
	at com.intellij.openapi.options.CompositeConfigurable.getConfigurables(CompositeConfigurable.java:61)
	at com.goide.configuration.GoLibrariesConfigurableProvider$1.createComponent(GoLibrariesConfigurableProvider.java:70)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel$1.compute(ConfigurableCardPanel.java:54)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel$1.compute(ConfigurableCardPanel.java:51)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.create(ConfigurableCardPanel.java:51)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:64)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:61)
	at com.intellij.ui.CardLayoutPanel.createValue(CardLayoutPanel.java:73)
	at com.intellij.ui.CardLayoutPanel.select(CardLayoutPanel.java:101)
	at com.intellij.ui.CardLayoutPanel.select(CardLayoutPanel.java:86)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor.<init>(ConfigurableEditor.java:102)
	at com.intellij.openapi.options.newEditor.SettingsDialog.<init>(SettingsDialog.java:48)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.editConfigurable(ShowSettingsUtilImpl.java:249)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.editConfigurable(ShowSettingsUtilImpl.java:223)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.editConfigurable(ShowSettingsUtilImpl.java:212)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.editConfigurable(ShowSettingsUtilImpl.java:196)
	at com.goide.project.GoModuleLibrariesInitializer.showModulesConfigurable(GoModuleLibrariesInitializer.java:313)
	at com.goide.inspections.WrongSdkConfigurationNotificationProvider$4.run(WrongSdkConfigurationNotificationProvider.java:119)
	at com.intellij.ui.EditorNotificationPanel$2.hyperlinkActivated(EditorNotificationPanel.java:93)
	at com.intellij.ui.HyperlinkAdapter.hyperlinkUpdate(HyperlinkAdapter.java:28)
	at com.intellij.ui.HyperlinkLabel.fireHyperlinkEvent(HyperlinkLabel.java:188)
	at com.intellij.ui.HyperlinkLabel.processMouseEvent(HyperlinkLabel.java:121)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4530)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2015-06-28 12:53:52,772 [  53281]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 14.1.3  Build #IC-141.1010.3 
2015-06-28 12:53:52,772 [  53281]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_45 
2015-06-28 12:53:52,772 [  53281]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-06-28 12:53:52,772 [  53281]  ERROR - llij.ide.plugins.PluginManager - Vendor: Oracle Corporation 
2015-06-28 12:53:52,772 [  53281]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
```

**Comment by zolotov** [comment]
As well as on IDEA 13/12/11/etc., don't see any reason to fix it.

**Comment by dlsniper** [comment]
ah, ok, so it's just a problem if I compile against a higher version of IDEA. Thought so but I wasn't sure so I preferred to ask. Thank you!
