### ISSUE TITLE
Exception on test run

### ISSUE THREAD

**Issue by dmitry-vovk** [go-lang-plugin-org/go-lang-idea-plugin#1717]
I observe an exception reported by IDEA in go plugin. It happens when I right click in editor window that contains tests and choose "Run \<current file name\>" command. The same happens when I run tests using Run toolbar window.

This is what I see in events log:
```
NoSuchMethodError: com.goide.runconfig.testing.GoTestConsoleProperties.getConfiguration()Lcom/intellij/execution/configurations/RunConfiguration;
```

Here is the trace:
```
com.goide.runconfig.testing.GoTestConsoleProperties.getConfiguration()Lcom/intellij/execution/configurations/RunConfiguration;
java.lang.NoSuchMethodError: com.goide.runconfig.testing.GoTestConsoleProperties.getConfiguration()Lcom/intellij/execution/configurations/RunConfiguration;
	at com.goide.runconfig.testing.GoTestConsoleProperties.createTestEventsConverter(GoTestConsoleProperties.java:36)
	at com.intellij.execution.testframework.sm.SMTestRunnerConnectionUtil.a(SMTestRunnerConnectionUtil.java:180)
	at com.intellij.execution.testframework.sm.SMTestRunnerConnectionUtil.access$000(SMTestRunnerConnectionUtil.java:51)
	at com.intellij.execution.testframework.sm.SMTestRunnerConnectionUtil$3.onAttachToProcess(SMTestRunnerConnectionUtil.java:328)
	at com.intellij.execution.testframework.sm.runner.ui.SMTRunnerConsoleView.attachToProcess(SMTRunnerConsoleView.java:144)
	at com.goide.runconfig.testing.GoTestRunningState.execute(GoTestRunningState.java:69)
	at com.intellij.execution.runners.DefaultProgramRunner.doExecute(DefaultProgramRunner.java:33)
	at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
	at com.intellij.execution.impl.ExecutionManagerImpl$5.run(ExecutionManagerImpl.java:367)
	at com.intellij.execution.impl.ExecutionManagerImpl.compileAndRun(ExecutionManagerImpl.java:280)
	at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.java:410)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:40)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:64)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:31)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:53)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:31)
	at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:94)
	at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:105)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$400(ExecutionManagerImpl.java:62)
	at com.intellij.execution.impl.ExecutionManagerImpl$7.run(ExecutionManagerImpl.java:494)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:352)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:335)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:319)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:844)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:393)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
Plugin: 0.9.375 and 0.9.376
IDEA: 142.2887.3

**Comment by onedotover** [comment]
I'm having the exact same issue with nearly identical output. 
OSX: 10.10.4
Plugin: 0.9.462
PhpStorm: 142.4912
```
com.goide.runconfig.testing.GoTestConsoleProperties.getConfiguration()Lcom/intellij/execution/configurations/RunConfiguration;
java.lang.NoSuchMethodError: com.goide.runconfig.testing.GoTestConsoleProperties.getConfiguration()Lcom/intellij/execution/configurations/RunConfiguration;
	at com.goide.runconfig.testing.GoTestConsoleProperties.createTestEventsConverter(GoTestConsoleProperties.java:36)
	at com.intellij.execution.testframework.sm.SMTestRunnerConnectionUtil.a(SMTestRunnerConnectionUtil.java:183)
	at com.intellij.execution.testframework.sm.SMTestRunnerConnectionUtil.access$000(SMTestRunnerConnectionUtil.java:54)
	at com.intellij.execution.testframework.sm.SMTestRunnerConnectionUtil$3.onAttachToProcess(SMTestRunnerConnectionUtil.java:331)
	at com.intellij.execution.testframework.sm.runner.ui.SMTRunnerConsoleView.attachToProcess(SMTRunnerConsoleView.java:144)
	at com.goide.runconfig.testing.GoTestRunningState.execute(GoTestRunningState.java:69)
	at com.intellij.execution.runners.DefaultProgramRunner.doExecute(DefaultProgramRunner.java:33)
	at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
	at com.intellij.execution.impl.ExecutionManagerImpl$5.run(ExecutionManagerImpl.java:376)
	at com.intellij.execution.impl.ExecutionManagerImpl.compileAndRun(ExecutionManagerImpl.java:289)
	at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.java:419)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:40)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:61)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:31)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:50)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:31)
	at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:94)
	at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:114)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$400(ExecutionManagerImpl.java:65)
	at com.intellij.execution.impl.ExecutionManagerImpl$7.run(ExecutionManagerImpl.java:503)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:352)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by dlsniper** [comment]
@onedotover IntelliJ 142.* branch is not supported yet. Please use a supported IDE listed in the readme and report again. Thank you.

**Comment by onedotover** [comment]
Ah sorry! I thought I had checked that. It does work on 141.2462. Thank you for the quick response and this great plugin.
