### ISSUE TITLE
Stub and PSI element type mismatch in FILE.go: stub GoTypeStub, AST SPEC_TYPE; Element(SPEC_TYPE)

### ISSUE THREAD

**Issue by ffissore** [go-lang-plugin-org/go-lang-idea-plugin#1812]
```
Stub and PSI element type mismatch in FILE.go: stub GoTypeStub, AST SPEC_TYPE; Element(SPEC_TYPE)
 file=GO_FILE, file.class=class com.goide.psi.GoFile, file.lang=Language: go, modStamp=0
 tree consistent
 stub debugInfo=created in getStubTree(); with backReference
 document before=DocumentImpl[file:///HIDDEN_PATH/FILE.go]
latestIndexedStub=com.intellij.psi.stubs.StubTree@f766645
   same size=true
   debugInfo=created from index; with backReference
 viewProvider=SingleRootFileViewProvider{myVirtualFile=file:///HIDDEN_PATH/FILE.go, content=VirtualFileContent{size=1074}}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1439904880158; file length: 1074
 doc saved: true; doc stamp: 0; doc size: 1074; committed: true
in many projects: false
indexing info: indexed at 1439904880158 with size 1074
------------

java.lang.AssertionError: Stub and PSI element type mismatch in FILE.go: stub GoTypeStub, AST SPEC_TYPE; Element(SPEC_TYPE)
 file=GO_FILE, file.class=class com.goide.psi.GoFile, file.lang=Language: go, modStamp=0
 tree consistent
 stub debugInfo=created in getStubTree(); with backReference
 document before=DocumentImpl[file:///HIDDEN_PATH/FILE.go]
latestIndexedStub=com.intellij.psi.stubs.StubTree@f766645
   same size=true
   debugInfo=created from index; with backReference
 viewProvider=SingleRootFileViewProvider{myVirtualFile=file:///HIDDEN_PATH/FILE.go, content=VirtualFileContent{size=1074}}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1439904880158; file length: 1074
 doc saved: true; doc stamp: 0; doc size: 1074; committed: true
in many projects: false
indexing info: indexed at 1439904880158 with size 1074
------------

	at com.intellij.psi.impl.source.PsiFileImpl.reportStubAstMismatch(PsiFileImpl.java:314)
	at com.intellij.psi.impl.source.PsiFileImpl$1.visitNode(PsiFileImpl.java:280)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitComposite(RecursiveTreeElementWalkingVisitor.java:80)
	at com.intellij.psi.impl.source.tree.CompositeElement.acceptTree(CompositeElement.java:158)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor$1.visit(RecursiveTreeElementWalkingVisitor.java:66)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor$1.visit(RecursiveTreeElementWalkingVisitor.java:58)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitNode(RecursiveTreeElementWalkingVisitor.java:85)
	at com.intellij.psi.impl.source.PsiFileImpl$1.visitNode(PsiFileImpl.java:289)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitComposite(RecursiveTreeElementWalkingVisitor.java:80)
	at com.intellij.psi.impl.source.tree.CompositeElement.acceptTree(CompositeElement.java:158)
	at com.intellij.psi.impl.source.PsiFileImpl.calcStubAstBindings(PsiFileImpl.java:263)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:189)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:743)
	at com.intellij.psi.impl.source.PsiFileImpl.getNode(PsiFileImpl.java:948)
	at com.intellij.psi.impl.source.PsiFileImpl.getNode(PsiFileImpl.java:64)
	at com.goide.formatter.GoFormattingModelBuilder.createModel(GoFormattingModelBuilder.java:49)
	at com.intellij.psi.codeStyle.autodetect.FormatterBasedLineIndentInfoBuilder.getBlocksStartingNewLine(FormatterBasedLineIndentInfoBuilder.java:102)
	at com.intellij.psi.codeStyle.autodetect.FormatterBasedLineIndentInfoBuilder.build(FormatterBasedLineIndentInfoBuilder.java:60)
	at com.intellij.psi.codeStyle.autodetect.IndentOptionsDetectorImpl.calcLineIndentInfo(IndentOptionsDetectorImpl.java:69)
	at com.intellij.psi.codeStyle.autodetect.IndentOptionsDetectorImpl.getIndentOptions(IndentOptionsDetectorImpl.java:57)
	at com.intellij.psi.codeStyle.autodetect.DetectableIndentOptionsProvider.getIndentOptions(DetectableIndentOptionsProvider.java:53)
	at com.intellij.psi.codeStyle.CodeStyleSettings.getIndentOptionsByFile(CodeStyleSettings.java:643)
	at com.intellij.psi.codeStyle.CodeStyleSettings.getIndentOptionsByFile(CodeStyleSettings.java:609)
	at com.intellij.psi.codeStyle.CodeStyleSettings.getIndentOptionsByFile(CodeStyleSettings.java:604)
	at com.intellij.openapi.editor.impl.SettingsImpl.getTabSize(SettingsImpl.java:324)
	at com.intellij.openapi.editor.ex.util.EditorUtil.getTabSize(EditorUtil.java:561)
	at com.intellij.openapi.editor.ex.util.EditorUtil.nextTabStop(EditorUtil.java:565)
	at com.intellij.openapi.editor.impl.EditorImpl$EditorSizeContainer.validateSizes(EditorImpl.java:6867)
	at com.intellij.openapi.editor.impl.EditorImpl$EditorSizeContainer.getContentSize(EditorImpl.java:6930)
	at com.intellij.openapi.editor.impl.EditorImpl$EditorSizeContainer.access$6800(EditorImpl.java:6616)
	at com.intellij.openapi.editor.impl.EditorImpl.getSizeWithoutCaret(EditorImpl.java:3806)
	at com.intellij.openapi.editor.impl.EditorImpl.getPreferredSize(EditorImpl.java:3782)
	at com.intellij.openapi.editor.impl.EditorImpl.<init>(EditorImpl.java:567)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:193)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:169)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.createEditor(TextEditorComponent.java:175)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.<init>(TextEditorComponent.java:106)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$PsiAwareTextEditorComponent.<init>(PsiAwareTextEditorImpl.java:62)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$PsiAwareTextEditorComponent.<init>(PsiAwareTextEditorImpl.java:55)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.createEditorComponent(PsiAwareTextEditorImpl.java:44)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.<init>(TextEditorImpl.java:46)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.<init>(PsiAwareTextEditorImpl.java:38)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider$1.build(PsiAwareTextEditorProvider.java:77)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$12.run(FileEditorManagerImpl.java:861)
	at com.intellij.util.ui.UIUtil.invokeAndWaitIfNeeded(UIUtil.java:2308)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:844)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl3(FileEditorManagerImpl.java:777)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$9.run(FileEditorManagerImpl.java:757)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:117)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:754)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:695)
	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.openFile(FileEditorManagerEx.java:146)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$15.run(FileEditorManagerImpl.java:1130)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openEditor(FileEditorManagerImpl.java:1126)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigateInAnyFileEditor(OpenFileDescriptor.java:146)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigateInEditor(OpenFileDescriptor.java:132)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigateInEditorOrNativeApp(OpenFileDescriptor.java:128)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigate(OpenFileDescriptor.java:115)
	at com.intellij.psi.impl.source.PsiFileImpl.navigate(PsiFileImpl.java:926)
	at com.intellij.codeInsight.navigation.NavigationUtil.openFileWithPsiElement(NavigationUtil.java:179)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.navigate(AbstractPsiBasedNode.java:207)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.navigate(AbstractPsiBasedNode.java:217)
	at com.intellij.ide.projectView.impl.nodes.PsiFileNode.navigate(PsiFileNode.java:132)
	at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:53)
	at com.intellij.util.OpenSourceUtil.openSourcesFrom(OpenSourceUtil.java:31)
	at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.processDoubleClick(EditSourceOnDoubleClickHandler.java:130)
	at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.onDoubleClick(EditSourceOnDoubleClickHandler.java:122)
	at com.intellij.ui.DoubleClickListener.onClick(DoubleClickListener.java:30)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:73)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:421)
	at com.intellij.ide.dnd.aware.DnDAwareTree.processMouseEvent(DnDAwareTree.java:58)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:643)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:378)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by dlsniper** [comment]
Hi, thanks for reporting. When did this happen? What are the steps to reproduce? Which IDE did you use? Also, the plugin supports the builtin reporting feature from the IDE, have you used that to report the error? Thank you.

**Comment by ffissore** [comment]
The error occurs *often* after double clicking (opening) a file. It's logged by the IDE which asks me to report to jetbrains. I pasted the content of the two fields popup it shows.
Plugin version is 0.9.460
IDEA version is IC-142.3926

**Comment by dlsniper** [comment]
Did you upgraded from a previous version of the plugin to this? Or did you upgraded the IDE before this started to happen?

As far as I know the plugin should be used with the stable release of IDEA for now, but not sure if that applies to the alpha release as well or just nightly.

Also, sending a report to JetBrains and pasting the URL of the report here would help out (there's a bit of extra information sent that helps tracing the issue, nothing private, the report itself is visible only to you and other JetBrains employes).

A quick way to "fix" this would be to use File -> Invalidate Caches / Restart -> Invalidate & Restart but that potentially means there's no way to extract more information about this and find a proper fix. Thank you.

I'd leave this to @ignatov to further investigate.

Thanks.

**Comment by ffissore** [comment]
I've been using your ALPHAs for a while now, so yes, I did upgrade from a previous plugin version.
After having invalidated caches and randomly clicked, I'm not able to reproduce the error any more. Thanks!

**Comment by dlsniper** [comment]
Cool. I'd highly suggest to switch to IDEA 14 meanwhile (unless you really need something from IDEA 15), there are some goodies that will come for it soon ;)

**Comment by dlsniper** [comment]
I guess we can close this one as well.
