### ISSUE TITLE
ConnectException when using dlv with a binary that can't be compiled

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1814]
When running a program that won't compile due to an error in the app this exception will happen:

```
[ 173383]  ERROR - jetbrains.rpc.CommandProcessor - Connection refused 
java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:244)
	at org.jetbrains.io.NettyUtil.doConnect(NettyUtil.java:157)
	at org.jetbrains.io.NettyUtil.connect(NettyUtil.java:105)
	at org.jetbrains.debugger.connection.RemoteVmConnection$1.run(RemoteVmConnection.java:77)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
[ 173383]  ERROR - jetbrains.rpc.CommandProcessor - IntelliJ IDEA 14.1.4  Build #IC-141.SNAPSHOT 
[ 173383]  ERROR - jetbrains.rpc.CommandProcessor - JDK: 1.8.0_60 
[ 173383]  ERROR - jetbrains.rpc.CommandProcessor - VM: Java HotSpot(TM) 64-Bit Server VM 
[ 173384]  ERROR - jetbrains.rpc.CommandProcessor - Vendor: Oracle Corporation 
[ 173384]  ERROR - jetbrains.rpc.CommandProcessor - OS: Linux 
[ 173384]  ERROR - jetbrains.rpc.CommandProcessor - Last Action: Debug
```

Plugin compiled from revision: b1fe90b7d4474ee9552fddc6045153720303e275

**Comment by ignatov** [comment]
Do you have any sample for reproducing?

**Comment by dlsniper** [comment]
I'll try and come with one but basically any code that's not compilable should do it:

```go
package main

func main() {
    println("demo)
}
```

I'll test this soon.

**Comment by dlsniper** [comment]
Hmmm, seems I can't reproduce with the plugin version I have anymore. Sorry. I'll close this for now.
