### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1881]
Hi,

I've compiled the plugin against IDEA 14.1.4 with commit 066753a2c5dbb144722cb9fec1dd0e87ef3cec4c. Before I was on commit: acd069ad7b020575dfee9b0e35b7b64e5ac8942e and things worked well.

The problem is that now I get a lot of these errors:
```
2015-09-19 19:48:07,812 [  13142]  ERROR - napi.project.CacheUpdateRunner - Error while indexing /home/florin/golang/src/github.com/awslabs/aws-sdk-go/service/codepipeline/codepipelineiface/interface_test.go
To reindex this file IDEA has to be restarted 
java.lang.NoClassDefFoundError: com/intellij/psi/tree/StubFileElementType
	at com.goide.GoFileElementType$1.createStubForFile(GoFileElementType.java:53)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTree(DefaultStubBuilder.java:36)
	at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:102)
	at com.intellij.psi.stubs.StubUpdatingIndex$3$1.run(StubUpdatingIndex.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:867)
	at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:123)
	at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:117)
	at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:398)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1744)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1674)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1622)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:101)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:97)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:292)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:312)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:306)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
Caused by: java.lang.ClassNotFoundException: com.intellij.psi.tree.StubFileElementType PluginClassLoader[ro.redeul.google.go, 1.0]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 30 more
2015-09-19 19:48:07,812 [  13142]  ERROR - napi.project.CacheUpdateRunner - IntelliJ IDEA 14.1.4  Build #IU-141.1532.4 
2015-09-19 19:48:07,812 [  13142]  ERROR - napi.project.CacheUpdateRunner - JDK: 1.8.0_60 
2015-09-19 19:48:07,812 [  13142]  ERROR - napi.project.CacheUpdateRunner - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-09-19 19:48:07,812 [  13142]  ERROR - napi.project.CacheUpdateRunner - Vendor: Oracle Corporation 
2015-09-19 19:48:07,812 [  13142]  ERROR - napi.project.CacheUpdateRunner - OS: Linux 
2015-09-19 19:48:07,812 [  13142]  ERROR - napi.project.CacheUpdateRunner - Last Action:  
```

It seems to happen for every go file indexed from the GOPATH.
Is there anything else that I can help to investigate this? Thank you.

**Comment by dlsniper** [comment]
After further investigation it seems there's something wrong in my environment as I've reverted to a previously known commit and I still receive the same error.

**Comment by dlsniper** [comment]
I've "fixed" this by running `git clean -f -x -d` in the git repository of the plugin and then doing a clean build from master. I guess there was some strange caching involved. Sorry for the noise.
