### ISSUE TITLE
I can not install the SDK Go (IntelliJ IDEA 14.1.4, JDK 1.6.0_65)

### ISSUE THREAD

**Issue by uilannor** [go-lang-plugin-org/go-lang-idea-plugin#1918]
I can not install the SDK Go. Tried version Go 1.4.3, 1.5.0, 1.5.1.
Envs GOROOT and GOPATH is installed.

OS X El Capitan (10.10.5), IntelliJ IDEA 14.1.4, JDK 1.6.0_65.
Version plugin: 0.9.15.3

Error in the terminal when choosing directory Go settings (Project Structure -> SDK):
```
[  25863]  ERROR - llij.ide.plugins.PluginManager - Argument for @NotNull parameter 'virtualFile' of com/intellij/openapi/projectRoots/impl/ProjectRootContainerImpl.addRoot must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'virtualFile' of com/intellij/openapi/projectRoots/impl/ProjectRootContainerImpl.addRoot must not be null
	at com.intellij.openapi.projectRoots.impl.ProjectRootContainerImpl.addRoot(ProjectRootContainerImpl.java)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkImpl.addRoot(ProjectJdkImpl.java:368)
	at ro.redeul.google.go.config.sdk.GoSdkType$2.run(GoSdkType.java:175)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
	at ro.redeul.google.go.config.sdk.GoSdkType.setupSdkPaths(GoSdkType.java:173)
	at com.intellij.openapi.projectRoots.SdkType.setupSdkPaths(SdkType.java:85)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.a(ProjectSdksModel.java:284)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.access$200(ProjectSdksModel.java:48)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel$5.consume(ProjectSdksModel.java:275)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel$5.consume(ProjectSdksModel.java:269)
	at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil$7.consume(SdkConfigurationUtil.java:289)
	at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil$7.consume(SdkConfigurationUtil.java:284)
	at com.intellij.ui.mac.MacFileChooserDialogImpl$3$2.run(MacFileChooserDialogImpl.java:153)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:205)
	at java.awt.Dialog$1.run(Dialog.java:1049)
	at java.awt.Dialog$3.run(Dialog.java:1101)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Dialog.show(Dialog.java:1099)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:778)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:465)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1614)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1571)
	at com.intellij.ide.actions.ShowStructureSettingsAction.showDialog(ShowStructureSettingsAction.java:43)
	at com.intellij.ide.actions.TemplateProjectStructureAction.actionPerformed(TemplateProjectStructureAction.java:25)
	at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrame$FlatWelcomeScreen$IconsFreeActionGroup$1.actionPerformed(FlatWelcomeFrame.java:567)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:746)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
[  25865]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 14.1.4  Build #IU-141.1532.4
[  25865]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.6.0_65
[  25865]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM
[  25865]  ERROR - llij.ide.plugins.PluginManager - Vendor: Apple Inc.
[  25865]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X
```

**Comment by dlsniper** [comment]
Please read the readme to help you get the latest and greatest version of the plugin which has this issue fixed. https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds
