### ISSUE TITLE
New Project window doesn't see the SDK directory

### ISSUE THREAD

**Issue by mfateev** [go-lang-plugin-org/go-lang-idea-plugin#1936]
I've installed go plugin and the Go SDK using mac installer. My GOROOT is set correctly, but New Project dialog still doesn't show the SDK in the list of available SDKs. Pressing "Configure" opens the correct go installation directory and pressing choose succeeds, but SDK still doesn't appear in the list.

Here is the logged exception:

2015-10-21 16:01:48,406 [ 176529]  ERROR - llij.ide.plugins.PluginManager - Argument for @NotNull parameter 'virtualFile' of com/intellij/openapi/projectRoots/impl/ProjectRootContainerImpl.addRoot must not be null 
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'virtualFile' of com/intellij/openapi/projectRoots/impl/ProjectRootContainerImpl.addRoot must not be null
	at com.intellij.openapi.projectRoots.impl.ProjectRootContainerImpl.addRoot(ProjectRootContainerImpl.java)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkImpl.addRoot(ProjectJdkImpl.java:368)
	at ro.redeul.google.go.config.sdk.GoSdkType$2.run(GoSdkType.java:175)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
	at ro.redeul.google.go.config.sdk.GoSdkType.setupSdkPaths(GoSdkType.java:173)
	at com.intellij.openapi.projectRoots.SdkType.setupSdkPaths(SdkType.java:85)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.a(ProjectSdksModel.java:284)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.access$200(ProjectSdksModel.java:48)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel$5.consume(ProjectSdksModel.java:275)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel$5.consume(ProjectSdksModel.java:269)
	at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil$7.consume(SdkConfigurationUtil.java:289)
	at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil$7.consume(SdkConfigurationUtil.java:284)
	at com.intellij.ui.mac.MacFileChooserDialogImpl$3$2.run(MacFileChooserDialogImpl.java:153)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:778)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:465)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1614)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1571)
	at com.intellij.openapi.ui.DialogWrapper.showAndGet(DialogWrapper.java:1578)
	at com.intellij.ide.impl.NewProjectUtil.createNewProject(NewProjectUtil.java:70)
	at com.intellij.ide.actions.NewProjectAction.actionPerformed(NewProjectAction.java:31)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:312)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:193)
	at java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:389)
	at java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:357)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2015-10-21 16:01:48,407 [ 176530]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 14.1.5  Build #IU-141.2735.5 
2015-10-21 16:01:48,407 [ 176530]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_60 
2015-10-21 16:01:48,407 [ 176530]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-10-21 16:01:48,407 [ 176530]  ERROR - llij.ide.plugins.PluginManager - Vendor: Oracle Corporation 
2015-10-21 16:01:48,407 [ 176530]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X 
2015-10-21 16:01:48,407 [ 176530]  ERROR - llij.ide.plugins.PluginManager - Last Action: NewProject 

Here are details of the go installation:

Maxim-Mac:IntelliJIdea14 maxim$ env|grep GO
GOROOT=/usr/local/go
GOPATH=/Users/maxim/gocode
Maxim-Mac:IntelliJIdea14 maxim$ go version
go version go1.5.1 darwin/amd64
Maxim-Mac:IntelliJIdea14 maxim$ which go
/usr/local/go/bin/go
Maxim-Mac:IntelliJIdea14 maxim$ ls $GOROOT
AUTHORS		CONTRIBUTORS	PATENTS		VERSION		bin		doc		lib		pkg		src
CONTRIBUTING.md	LICENSE		README.md	api		blog		favicon.ico	misc		robots.txt	test

**Comment by dlsniper** [comment]
Please use search feature from Github :) The problem is discussed in a dozen issues by now. Please read the readme for how to fix the issue: https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds
