### ISSUE TITLE
Plugin 'ro.redeul.google.go' failed to initialize and will be disabled

### ISSUE THREAD

**Issue by alexcc4** [go-lang-plugin-org/go-lang-idea-plugin#1963]
Hello, I just install your plugin, and nothing wrong happen except I  restart the IDE. It rises the problem like below:

Plugin 'ro.redeul.google.go' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NoClassDefFoundError: com/goide/GoConstants
    at com.goide.ui.ProjectTutorialNotification.initComponent(ProjectTutorialNotification.java:49)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:568)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:610)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:245)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:125)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:354)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:116)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:87)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:499)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:481)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:170)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:62)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:362)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.goide.GoConstants PluginClassLoader[ro.redeul.google.go, 1.0]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 29 more

My JDK version is 8 , any solution? THX...

**Comment by dlsniper** [comment]
Hi, 

Which IDE and what version are you using? 
Thanks

**Comment by alexcc4** [comment]
IntelliJ 14

**Comment by alexcc4** [comment]
I refers to https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1203, and may be I will work.

**Comment by dlsniper** [comment]
IntelliJ IDEA 14 is not supported, 14.1 and 15 are supported. Can you please try one of those? Thank you.

**Comment by zolotov** [comment]
Hi @alexcc4, how did you install the plugin? And what version?

**Comment by alexcc4** [comment]
@zolotov  Yep. I just download the IntelliJ plugin in its official website https://plugins.jetbrains.com/plugin/5047 of 0.9.562 version. It works after it was load into IntelliJ. It's much straghtforward than complie source code by myself.
