### ISSUE TITLE
Run no longer works when project contains syntax errors

### ISSUE THREAD

**Issue by DmitriyMV** [go-lang-plugin-org/go-lang-idea-plugin#1980]
* Idea 15
* Windows 10
* Plugin version 0.10.621

When I try to run project (Run kind: Package) which contains syntax errors, nothing is reported back to me.

**Comment by dlsniper** [comment]
Can you please add a code sample to reproduce this? For me it works, please see below:

![snapshot129](https://cloud.githubusercontent.com/assets/607868/11049494/f77e148c-873e-11e5-8d3c-ae425fe94bd6.png)

Thank you.

**Comment by DmitriyMV** [comment]
Found the root cause - calling gotype ( #1967 ) somehow affects this. More importantly - even IDEA restart doesn't help - only full PC reboot. Any way to investigate why?

**Comment by DmitriyMV** [comment]
Ok - now I think i broke something:
Found this in log files
```
2015-11-10 05:20:37,652 [ 180517]  ERROR - ecution.process.ProcessHandler - null 
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.execution.process.ProcessHandler$4.invoke(ProcessHandler.java:214)
	at com.sun.proxy.$Proxy14.processTerminated(Unknown Source)
	at com.intellij.execution.process.ProcessHandler$3.run(ProcessHandler.java:171)
	at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:247)
	at com.intellij.execution.process.ProcessHandler.notifyTerminated(ProcessHandler.java:153)
	at com.intellij.execution.process.ProcessHandler.notifyProcessTerminated(ProcessHandler.java:149)
	at com.intellij.execution.process.KillableColoredProcessHandler.notifyProcessTerminated(KillableColoredProcessHandler.java:127)
	at com.intellij.execution.process.BaseOSProcessHandler.onOSProcessTerminated(BaseOSProcessHandler.java:150)
	at com.intellij.execution.process.BaseOSProcessHandler$1$1.consume(BaseOSProcessHandler.java:115)
	at com.intellij.execution.process.BaseOSProcessHandler$1$1.consume(BaseOSProcessHandler.java:100)
	at com.intellij.execution.process.ProcessWaitFor$1.run(ProcessWaitFor.java:55)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.pty4j.unix.PtyHelpers
	at com.goide.util.GoExecutor$1.processTerminated(GoExecutor.java:211)
	... 21 more
2015-11-10 05:20:37,652 [ 180517]  ERROR - ecution.process.ProcessHandler - IntelliJ IDEA 15.0  Build #IC-143.381.42 
2015-11-10 05:20:37,652 [ 180517]  ERROR - ecution.process.ProcessHandler - JDK: 1.8.0_51 
2015-11-10 05:20:37,652 [ 180517]  ERROR - ecution.process.ProcessHandler - VM: Java HotSpot(TM) Server VM 
2015-11-10 05:20:37,652 [ 180517]  ERROR - ecution.process.ProcessHandler - Vendor: Oracle Corporation 
2015-11-10 05:20:37,652 [ 180517]  ERROR - ecution.process.ProcessHandler - OS: Windows 8 
2015-11-10 05:20:37,652 [ 180517]  ERROR - ecution.process.ProcessHandler - Last Action: Run 
2015-11-10 05:20:41,150 [ 184015]   INFO - j.compiler.server.BuildManager - Clearing project build data because the project does not exist or was not opened for more than 30 days: C:\Users\Dmitry\.IdeaIC15\system\compile-server\androidrest_7ad5c7f7 
2015-11-10 05:20:41,150 [ 184015]   INFO - j.compiler.server.BuildManager - Clearing project build data because the project does not exist or was not opened for more than 30 days: C:\Users\Dmitry\.IdeaIC15\system\compile-server\tempproject_76ffb414 
2015-11-10 05:21:02,096 [ 204961]  ERROR - ecution.process.ProcessHandler - null 
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.execution.process.ProcessHandler$4.invoke(ProcessHandler.java:214)
	at com.sun.proxy.$Proxy14.processTerminated(Unknown Source)
	at com.intellij.execution.process.ProcessHandler$3.run(ProcessHandler.java:171)
	at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:247)
	at com.intellij.execution.process.ProcessHandler.notifyTerminated(ProcessHandler.java:153)
	at com.intellij.execution.process.ProcessHandler.notifyProcessTerminated(ProcessHandler.java:149)
	at com.intellij.execution.process.KillableColoredProcessHandler.notifyProcessTerminated(KillableColoredProcessHandler.java:127)
	at com.intellij.execution.process.BaseOSProcessHandler.onOSProcessTerminated(BaseOSProcessHandler.java:150)
	at com.intellij.execution.process.BaseOSProcessHandler$1$1.consume(BaseOSProcessHandler.java:115)
	at com.intellij.execution.process.BaseOSProcessHandler$1$1.consume(BaseOSProcessHandler.java:100)
	at com.intellij.execution.process.ProcessWaitFor$1.run(ProcessWaitFor.java:55)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.pty4j.unix.PtyHelpers
	at com.goide.util.GoExecutor$1.processTerminated(GoExecutor.java:211)
	... 21 more
2015-11-10 05:21:02,096 [ 204961]  ERROR - ecution.process.ProcessHandler - IntelliJ IDEA 15.0  Build #IC-143.381.42 
2015-11-10 05:21:02,096 [ 204961]  ERROR - ecution.process.ProcessHandler - JDK: 1.8.0_51 
2015-11-10 05:21:02,096 [ 204961]  ERROR - ecution.process.ProcessHandler - VM: Java HotSpot(TM) Server VM 
2015-11-10 05:21:02,096 [ 204961]  ERROR - ecution.process.ProcessHandler - Vendor: Oracle Corporation 
2015-11-10 05:21:02,096 [ 204961]  ERROR - ecution.process.ProcessHandler - OS: Windows 8 
2015-11-10 05:21:02,096 [ 204961]  ERROR - ecution.process.ProcessHandler - Last Action: Run 
```
2015-11-10 05:20:37 run contains syntax error and
2015-11-10 05:20:41 run is syntax-error free. Second run's us usual and the first one doesn't produce anything.

**Comment by dlsniper** [comment]
Thanks for the follow up, I'll defer this to @zolotov

**Comment by zolotov** [comment]
@DmitriyMV sorry about that, please try the next nightly, I have no windows machine right now so I cannot verify the fix.

**Comment by DmitriyMV** [comment]
@zolotov @dlsniper thanks, working fine now.
