### ISSUE TITLE
Observing occasional NullPointerException with the plugin

### ISSUE THREAD

**Issue by lionelmessi** [go-lang-plugin-org/go-lang-idea-plugin#2299]
OS: Ubuntu 14.04
Android Studio: 1.5.1
Plugin: 0.9.1052

    java.lang.NullPointerException
	at com.goide.GoDocumentationProvider.replaceInnerTypes(GoDocumentationProvider.java:282)
	at com.goide.GoDocumentationProvider.replaceInnerTypes(GoDocumentationProvider.java:275)
	at com.goide.GoDocumentationProvider.getTypePresentation(GoDocumentationProvider.java:231)
	at com.goide.GoDocumentationProvider.getSignature(GoDocumentationProvider.java:153)
	at com.goide.GoDocumentationProvider.getQuickNavigateInfo(GoDocumentationProvider.java:367)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.getQuickNavigateInfo(CompositeDocumentationProvider.java:115)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.doGenerateInfo(CtrlMouseHandler.java:333)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.generateInfo(CtrlMouseHandler.java:324)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$1900(CtrlMouseHandler.java:104)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$InfoSingle$1.compute(CtrlMouseHandler.java:439)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$InfoSingle$1.compute(CtrlMouseHandler.java:435)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$InfoSingle.getInfo(CtrlMouseHandler.java:435)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.showHint(CtrlMouseHandler.java:858)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2800(CtrlMouseHandler.java:766)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$2.run(CtrlMouseHandler.java:833)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by zolotov** [comment]
@lionelmessi according to stacktrace, this NPE occurs when you hover some code with Ctrl+mouse, it would be nice to see the code that leads to this exception.

**Comment by lionelmessi** [comment]
I will try to find the code that is causing this. It is quite random. Also, I don't see any break of functionality after the NPE occurs.

**Comment by zolotov** [comment]
@lionelmessi thank you. With this exception you won't see doc balloon on hover and won't see any documentation on "Show Quick Documentation" action, that's all possible symptoms.

<img width="645" alt="screenshot 2016-01-25 11 07 48" src="https://cloud.githubusercontent.com/assets/140920/12545502/e48c1cc4-c353-11e5-9adf-1b3439977b0c.png">

<img width="311" alt="screenshot 2016-01-25 11 06 41" src="https://cloud.githubusercontent.com/assets/140920/12545503/eafc8d14-c353-11e5-846a-e23795f939d8.png">

**Comment by dlsniper** [comment]
I'll close this due to inactivity, if it still happens, please reopen it. Thank you.
