### ISSUE TITLE
Unable to save settings

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#2392]
- Plugin version (or commit hash): 0.11.1192
IntelliJ IDEA 2016.1
Build #IU-145.257, built on March 15, 2016
JRE: 1.8.0_76-release-b18 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Kubuntu 15.10

- What are you trying to do?
Nothing in particular, maybe switch applications can be used as an example

- What would you expect to happen?
Nothing

- What happens?
KotlinTypeCastException

Your issue description goes here.
I'm receiving these errors when I do actions that would trigger saving of settings (for example switching applications)
```
2016-03-16 20:37:11,546 [2921204]   WARN - mponents.impl.stores.StoreUtil - Save settings failed 
kotlin.TypeCastException: null cannot be cast to non-null type kotlin.ByteArray
	at com.intellij.configurationStore.StateMapKt.stateToElement(StateMap.kt:108)
	at com.intellij.configurationStore.StateMap.getElement(StateMap.kt:154)
	at com.intellij.configurationStore.XmlElementStorageKt.save(XmlElementStorage.kt:203)
	at com.intellij.configurationStore.XmlElementStorage$XmlElementStorageSaveSession.save(XmlElementStorage.kt:127)
	at com.intellij.configurationStore.FileBasedStorage$FileSaveSession.save(FileBasedStorage.kt:83)
	at com.intellij.configurationStore.ComponentStoreImplKt.executeSave(ComponentStoreImpl.kt:435)
	at com.intellij.configurationStore.ComponentStoreImpl.doSave(ComponentStoreImpl.kt:212)
	at com.intellij.configurationStore.ComponentStoreImpl.save(ComponentStoreImpl.kt:158)
	at com.intellij.configurationStore.ProjectWithModulesStoreImpl.beforeSave(ProjectStoreImpl.kt:365)
	at com.intellij.configurationStore.ProjectStoreImpl.doSave(ProjectStoreImpl.kt:239)
	at com.intellij.configurationStore.ComponentStoreImpl.save(ComponentStoreImpl.kt:158)
	at com.intellij.openapi.components.impl.stores.StoreUtil.save(StoreUtil.java:49)
	at com.intellij.openapi.project.impl.ProjectImpl.save(ProjectImpl.java:314)
	at com.intellij.ide.SaveAndSyncHandlerImpl.doSaveDocumentsAndProjectsAndApp(SaveAndSyncHandlerImpl.java:146)
	at com.intellij.ide.SaveAndSyncHandlerImpl.saveProjectsAndDocuments(SaveAndSyncHandlerImpl.java:134)
	at com.intellij.ide.SaveAndSyncHandlerImpl$4.onFrameDeactivated(SaveAndSyncHandlerImpl.java:104)
	at com.intellij.ide.FrameStateManagerImpl.a(FrameStateManagerImpl.java:87)
	at com.intellij.ide.FrameStateManagerImpl.access$500(FrameStateManagerImpl.java:32)
	at com.intellij.ide.FrameStateManagerImpl$2$1.run(FrameStateManagerImpl.java:72)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.util.Alarm$Request.run(Alarm.java:398)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Not sure if it's related to the plugin or IDE (maybe YouTrack would be a better place for this?)

**Comment by ignatov** [comment]
@develar Have you seen it?

**Comment by develar** [comment]
Already fixed in 146, will be cherry-picked to 145.

**Comment by dlsniper** [comment]
I'll close this then as I wasn't sure if it's the plugin / recent changes or the platform. Thank you.
