### ISSUE TITLE
stub mismatch

### ISSUE THREAD

**Issue by zolotov** [go-lang-plugin-org/go-lang-idea-plugin#2483]
Project: go sdk

```
[1208346]  ERROR - ex.GlobalInspectionContextImpl - In file: builtin.go 
java.lang.AssertionError: Stub list in utf16_test.go has more elements than PSI
 file=GO_FILE, file.class=class com.goide.psi.GoFile, file.lang=Language: go, modStamp=0
 tree consistent
 stub debugInfo=created in getStubTree(), no AST; with backReference
 document before=DocumentImpl[file:///Users/zolotov/dev/go/src/unicode/utf16/utf16_test.go]
latestIndexedStub=StubTree{myDebugInfo='created from index; with backReference', myRoot=GoFileStub}327894187
   same size=true
   debugInfo=created from index; with backReference
 viewProvider=SingleRootFileViewProvider{myVirtualFile=file:///Users/zolotov/dev/go/src/unicode/utf16/utf16_test.go, content=VirtualFileContent{size=5204}}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1457910109000; file length: 5204
 doc saved: true; doc stamp: 0; doc size: 5160; committed: true
in many projects: false
indexing info: indexed at 1457910109000 with size 5160
------------

	at com.intellij.psi.impl.source.PsiFileImpl.reportStubAstMismatch(PsiFileImpl.java:338)
	at com.intellij.psi.impl.source.PsiFileImpl.calcStubAstBindings(PsiFileImpl.java:321)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:196)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:799)
	at com.intellij.psi.impl.source.PsiFileImpl.getNode(PsiFileImpl.java:1004)
	at com.intellij.psi.impl.source.PsiFileImpl.getNode(PsiFileImpl.java:67)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTreeUp(LowLevelSearchUtil.java:77)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.access$000(LowLevelSearchUtil.java:42)
	at com.intellij.psi.impl.search.LowLevelSearchUtil$1.execute(LowLevelSearchUtil.java:199)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTextOccurrences(LowLevelSearchUtil.java:242)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsContainingWordInElement(LowLevelSearchUtil.java:195)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$3.processInReadAction(PsiSearchHelperImpl.java:230)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$3.processInReadAction(PsiSearchHelperImpl.java:226)
	at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:31)
	at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:28)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:962)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:28)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$6.compute(PsiSearchHelperImpl.java:385)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$6.compute(PsiSearchHelperImpl.java:367)
	at com.intellij.openapi.application.ex.ApplicationUtil$1.run(ApplicationUtil.java:37)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.openapi.application.ex.ApplicationUtil.tryRunReadAction(ApplicationUtil.java:34)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processVirtualFile(PsiSearchHelperImpl.java:367)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.access$100(PsiSearchHelperImpl.java:68)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$4.process(PsiSearchHelperImpl.java:314)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$4.process(PsiSearchHelperImpl.java:309)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:128)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:217)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:146)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:217)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:146)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:217)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:146)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:217)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:146)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:217)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:146)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:217)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:146)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:91)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:112)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:88)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by zolotov** [comment]
up

**Comment by ignatov** [comment]
Fixed with the latest JFlex – it uses Character.codePointAt() instead of charAt().
