### ISSUE TITLE
Stub mismatch

### ISSUE THREAD

**Issue by grenki** [go-lang-plugin-org/go-lang-idea-plugin#2540]
- Plugin version (or commit hash): commit c8689d26e86c5479eb84b17d248281ec7c00435f

- IDE name and version:IntelliJ IDEA 2016.1
Build #IC-145.258, built on March 17, 2016
- Java version: JRE: 1.8.0_91-b14 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
- OS name and version: Ubuntu 16.04 LTS

- What are you trying to do?
Open project with file main.go

- What happens?
```
[  11931]  ERROR - stubs.StubProcessingHelperBase - IdeaLoggingEvent[message=PSI and index do not match, throwable=Please report the problem to JetBrains with the file attached
 file=GO_FILE, file.class=class com.goide.psi.GoFile, file.lang=Language: go, modStamp=3
 tree consistent
 stub debugInfo=created in calcStubTree; with backReference
 document before=null
latestIndexedStub=StubTree{myDebugInfo='created from index; with backReference', myRoot=GoFileStub}1451512924
   same size=false
   debugInfo=created from index; with backReference
 viewProvider=SingleRootFileViewProvider{myVirtualFile=file:///home/user/IdeaProjects/go-test/main2.go, content=VirtualFileContent{size=328}}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1464178473557; file length: 328
 doc saved: true; doc stamp: 0; doc size: 328; committed: true
in many projects: false
indexing info: indexed at 1464178473557 with size 328
java.lang.Throwable
	at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:501)
	at com.intellij.psi.stubs.StubProcessingHelper.stubTreeAndIndexDoNotMatch(StubProcessingHelper.java:43)
	at com.intellij.psi.stubs.StubProcessingHelperBase.inconsistencyDetected(StubProcessingHelperBase.java:175)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:165)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:52)
	at com.intellij.psi.stubs.StubIndexImpl$1.process(StubIndexImpl.java:232)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:589)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:577)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:81)
	at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:258)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:224)
	at com.goide.stubs.index.GoFunctionIndex.process(GoFunctionIndex.java:60)
	at com.goide.inspections.GoDuplicateFunctionOrMethodInspection$1.visitFunctionDeclaration(GoDuplicateFunctionOrMethodInspection.java:91)
	at com.goide.psi.impl.GoFunctionDeclarationImpl.accept(GoFunctionDeclarationImpl.java:42)
	at com.goide.psi.impl.GoFunctionDeclarationImpl.accept(GoFunctionDeclarationImpl.java:46)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:294)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$200(LocalInspectionsPass.java:73)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:261)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:256)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:128)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:112)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:88)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
] 


```
file main.go:

```
package main

import (
	"fmt"
	"html/template"
)


func main (){

	var e template.IsTrue(struct{chan true})
	var a, w int
	var t struct {x int} = struct{x int }{1};

	a, w = asasd(1,t,lenz(w))


fmt.Println(w, w)
}
func asasd(int int, qe struct{ x int }, strings string) (int, int) {
}
func lenz(a int) string {
	return "asd"
}
```
[main.txt](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/281934/main.txt)

**Comment by ignatov** [comment]
Could you please attach the main2.go source code.

**Comment by grenki** [comment]
[main2.txt](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/331484/main2.txt)
GitHub doesn't support .go files.

**Comment by ignatov** [comment]
Obsolete
