### ISSUE TITLE
Problem with extract variable

### ISSUE THREAD

**Issue by grenki** [go-lang-plugin-org/go-lang-idea-plugin#2542]
[errorFile.txt](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/282169/errorFile.txt)

- Plugin version (or commit hash): commit c8689d26e86c5479eb84b17d248281ec7c00435f

IDE name and version: IntelliJ IDEA 2016.1
Build #IC-145.258, built on March 17, 2016
Java version: JRE: 1.8.0_91-b14 amd64 JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

OS name and version: Ubuntu 16.04 LTS

What are you trying to do?
Select assignment statement  ` i = g + 2`  and try extract variable

- What happens?
```
[  23446]  ERROR - inplace.VariableInplaceRenamer - PsiElement(identifier) by com.goide.refactor.GoIntroduceVariableBase$GoInplaceVariableIntroducer 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.intellij.refactoring.rename.inplace.InplaceRefactoring.getSelectedInEditorElement(InplaceRefactoring.java:747)
	at com.intellij.refactoring.rename.inplace.InplaceRefactoring.buildTemplateAndStart(InplaceRefactoring.java:281)
	at com.intellij.refactoring.rename.inplace.InplaceRefactoring.performInplaceRefactoring(InplaceRefactoring.java:212)
	at com.goide.refactor.GoIntroduceVariableBase.performInplaceIntroduce(GoIntroduceVariableBase.java:161)
	at com.goide.refactor.GoIntroduceVariableBase.access$000(GoIntroduceVariableBase.java:51)
	at com.goide.refactor.GoIntroduceVariableBase$3.pass(GoIntroduceVariableBase.java:145)
	at com.goide.refactor.GoIntroduceVariableBase$3.pass(GoIntroduceVariableBase.java:141)
	at com.intellij.refactoring.introduce.inplace.OccurrencesChooser.showChooser(OccurrencesChooser.java:81)
	at com.goide.refactor.GoIntroduceVariableBase.performOnElement(GoIntroduceVariableBase.java:141)
	at com.goide.refactor.GoIntroduceVariableBase.performAction(GoIntroduceVariableBase.java:79)
	at com.goide.refactor.GoIntroduceVariableHandler.invoke(GoIntroduceVariableHandler.java:32)
	at com.intellij.refactoring.actions.BaseRefactoringAction.actionPerformed(BaseRefactoringAction.java:134)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:191)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:311)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:281)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:513)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Example
```go
var i, g int
<selection>i = g + 2</selection>

```

**Comment by grenki** [comment]
Second problem:
I try extract variable, then select "replace this occurrence only"

```
var i, g struct{ x int }
i = g<caret>
```
```
[  54444]  ERROR - llij.ide.plugins.PluginManager - null 
java.lang.AssertionError
	at com.goide.refactor.GoIntroduceVariableBase$4.run(GoIntroduceVariableBase.java:183)
	at com.intellij.openapi.command.WriteCommandAction$4.run(WriteCommandAction.java:180)
	at com.intellij.openapi.command.WriteCommandAction$Simple.run(WriteCommandAction.java:162)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction$2.run(WriteCommandAction.java:108)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:103)
	at com.intellij.openapi.command.WriteCommandAction.access$000(WriteCommandAction.java:34)
	at com.intellij.openapi.command.WriteCommandAction$1.run(WriteCommandAction.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:723)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:82)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:182)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:169)
	at com.goide.refactor.GoIntroduceVariableBase.performReplace(GoIntroduceVariableBase.java:176)
	at com.goide.refactor.GoIntroduceVariableBase.performInplaceIntroduce(GoIntroduceVariableBase.java:160)
	at com.goide.refactor.GoIntroduceVariableBase.access$000(GoIntroduceVariableBase.java:51)
	at com.goide.refactor.GoIntroduceVariableBase$3.pass(GoIntroduceVariableBase.java:145)
	at com.goide.refactor.GoIntroduceVariableBase$3.pass(GoIntroduceVariableBase.java:141)
	at com.intellij.refactoring.introduce.inplace.OccurrencesChooser$5.run(OccurrencesChooser.java:146)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
[  54445]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2016.1  Build #IC-145.258.11 
[  54445]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_91 
[  54445]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM 
[  54445]  ERROR - llij.ide.plugins.PluginManager - Vendor: Oracle Corporation 
[  54445]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
[  66206]  ERROR - llij.ide.plugins.PluginManager - null 
```
