### ISSUE TITLE
Intellij 2016.2.2 debug hangs 

### ISSUE THREAD

**Issue by hhzguo** [go-lang-plugin-org/go-lang-idea-plugin#2773]
- Plugin version (or commit hash):1789
- IDE name and version: IntelliJ IDEA 2016.2.2 build #IC-162.1628.40
- Java version: JDK 1.8.0_76-release
- OS name and version:  Ubuntu 14.04

- What are you trying to do? 
Debug a go application with in IntelliJ IDe
- What would you expect to happen?

- What happens?
Debugger hangs, 
llij.ide.plugin.PluginManager -null  java.lang.NullPointerException
at com.goide.dlv.DlvStackFrame.customizePresentation(DlvStackFrame.java:144
at com.Intellij.xdebugger.impl.frame.XDebuggerFramesList$XDebuggerFrameListRenderer.customizeCellRenderer(XDebuggerFramesList.java:185)
at com.Intellij.ui.ColoredListCellRenderer.getListCellRendererComponent(ColoredListCellRenderer.java:76)
......
.....
....

Your issue description goes here.
Please be as detailed as possible

```go
Please include a go sample to reproduce the issue
```

Or include a screenshot / video of the issue.

**Comment by dlsniper** [comment]
Is there any way to reproduce the issue?

**Comment by hhzguo** [comment]
Florin:
My intellij us running on a ubuntu vm with vncserver, I connect it from a
windows box using tightvnc viewer
Hope this helps

Thx henry
2016年9月8日 11:10 AM，"Florin Pățan" <notifications@github.com>写道：

**Comment by zolotov** [comment]
Please follow the instructions https://intellij-support.jetbrains.com/hc/en-us/articles/207241235-Reporting-performance-problems

**Comment by hhzguo** [comment]
Open a Ubuntu 14.04 server Ubuntu
serup a vncserver (give the server system a "GUI")
Use TightVNC viewer to connect to the Ubuntu VM.
Install intellij with golang plugin.
Debug a program with "Debugger" tab displayed.
Debug the program  for a couple minutes
It is very easy to repro. ( I guess the bug is in "Debugger" view part, because if I don't display "Debugger" tab, it never occurs)

**Comment by zolotov** [comment]
I'm sorry but the answer is the same: please follow the instructions https://intellij-support.jetbrains.com/hc/en-us/articles/207241235-Reporting-performance-problems and attach at least thread dumps.

Do you still use plugin version 1789? What IDE do you use? what the program should I debug to recreate the issue?
