### ISSUE TITLE
"The selected directory is not a valid home for Go SDK"

### ISSUE THREAD

**Issue by yyrr001** [go-lang-plugin-org/go-lang-idea-plugin#2859]
- Plugin version (or commit hash):
Version: **0.13.1924**

- IDE name and version:
**IDEA 2016.3.2**

- Java version:
- OS name and version: 

windows 10

- What are you trying to do?
 set go SDK for project

- What would you expect to happen?

- What happens?
**"The selected directory is not a valid home for Go SDK"**

Your issue description goes here.
Please be as detailed as possible

```go
Please include a go sample to reproduce the issue
```

Or include a screenshot / video of the issue.
![image](https://cloud.githubusercontent.com/assets/16753656/21759172/31e49cfc-d67d-11e6-8b85-b9ffd4920c75.png)

![image](https://cloud.githubusercontent.com/assets/16753656/21759202/651153ae-d67d-11e6-9866-104bc2c00696.png)

![image](https://cloud.githubusercontent.com/assets/16753656/21759164/21fcdbba-d67d-11e6-90dc-20fbd2bb86e1.png)

**Comment by ignatov** [comment]
Please attach your logs '''Help > Show logs in...'''.

**Comment by yyrr001** [comment]
`2017-01-09 16:57:50,445 [   1467]   INFO - llij.ide.plugins.PluginManager - Loaded bundled plugins: Android Support (10.2.2), Ant Support (1.0), Bytecode Viewer (0.1), CVS Integration (11), Copyright (8.1), Coverage (163.10154.41), Eclipse Integration (3.0), EditorConfig (163.10154.41), Git Integration (8.1), GitHub (163.10154.41), Gradle (163.10154.41), Groovy (9.0), I18n for Java (163.10154.41), IDEA CORE (163.10154.41), IntelliLang (8.0), JUnit (1.0), Java Bytecode Decompiler (163.10154.41), JavaFX (1.0), Kotlin (1.0.5-release-IJ2016.3-1), Maven Integration (163.10154.41), Plugin DevKit (1.0), Properties Support (163.10154.41), Settings Repository (163.10154.41), Subversion Integration (1.1), Task Management (1.0), Terminal (0.1), TestNG-J (8.0), UI Designer (163.10154.41), XPathView + XSLT Support (4), XSLT-Debugger (1.4), YAML (163.10154.41), hg4idea (10.0) 
2017-01-09 16:57:50,445 [   1467]   INFO - llij.ide.plugins.PluginManager - **Loaded custom plugins: File Watchers (163.10154.19), Go (0.13.1924), Scala (2016.3.5)** 
2017-01-09 16:57:51,528 [   2550]   INFO - ellij.util.io.PagedFileStorage - lower=100; upper=500; buffer=10; max=705 
2017-01-09 16:57:51,646 [   2668]   INFO - pl.local.NativeFileWatcherImpl - Starting file watcher: D:\IntelliJ IDEA Community Edition 2016.3\bin\fsnotifier64.exe 
2017-01-09 16:57:51,689 [   2711]   INFO - pl.local.NativeFileWatcherImpl - Native file watcher is operational. 
2017-01-09 16:57:51,799 [   2821]   INFO - pi.util.registry.RegistryState - Registry values changed by user: 
2017-01-09 16:57:51,799 [   2821]   INFO - pi.util.registry.RegistryState -   SBT.system.in.process = true 
2017-01-09 16:57:51,799 [   2821]   INFO - pi.util.registry.RegistryState -   completion.show.intention.icon = false 
2017-01-09 16:57:52,553 [   3575]   INFO - rains.ide.BuiltInServerManager - built-in server started, port 63342 
2017-01-09 16:57:52,582 [   3604]   INFO - gs.impl.UpdateCheckerComponent - channel: release 
2017-01-09 16:57:52,688 [   3710]   INFO - il.indexing.FileBasedIndexImpl - Index exts enumerated:70 
2017-01-09 16:57:52,692 [   3714]   INFO - il.indexing.FileBasedIndexImpl - Index scheduled:3 
2017-01-09 16:57:52,720 [   3742]   INFO - tellij.psi.stubs.StubIndexImpl - All stub exts enumerated:22 
2017-01-09 16:57:52,721 [   3743]   INFO - tellij.psi.stubs.StubIndexImpl - stub exts update scheduled:0 
2017-01-09 16:57:52,754 [   3776]   INFO - j.ide.script.IdeStartupScripts - 0 startup script(s) found 
2017-01-09 16:57:53,138 [   4160]   INFO - il.indexing.FileBasedIndexImpl - Version has changed for index IdIndex. The index will be rebuilt. 
2017-01-09 16:57:53,152 [   4174]   INFO - plication.impl.ApplicationImpl - 95 application components initialized in 3673ms 
2017-01-09 16:57:53,172 [   4194]   INFO - .intellij.idea.IdeaApplication - App initialization took 5186 ms 
2017-01-09 16:57:53,252 [   4274]   INFO - il.indexing.FileBasedIndexImpl - Version has changed for index filetypes. The index will be rebuilt. 
2017-01-09 16:57:53,578 [   4600]   INFO - ellij.project.impl.ProjectImpl - 23 project components initialized in 873 ms 
2017-01-09 16:57:53,579 [   4601]   INFO - le.impl.ModuleManagerComponent - 0 module(s) loaded in 0 ms 
2017-01-09 16:57:54,069 [   5091]   INFO - ij.psi.stubs.StubUpdatingIndex - requesting complete stub index rebuild due to changes: added file types:Go; 
2017-01-09 16:57:54,069 [   5091]   INFO - il.indexing.FileBasedIndexImpl -  
java.io.IOException
	at com.intellij.psi.stubs.StubVersionMap.updateState(StubVersionMap.java:113)
	at com.intellij.psi.stubs.StubVersionMap.<init>(StubVersionMap.java:64)
	at com.intellij.psi.stubs.StubUpdatingIndex$MyIndex.<init>(StubUpdatingIndex.java:396)
	at com.intellij.psi.stubs.StubUpdatingIndex.createIndexImplementation(StubUpdatingIndex.java:337)
	at com.intellij.util.indexing.FileBasedIndexImpl.createIndex(FileBasedIndexImpl.java:455)
	at com.intellij.util.indexing.FileBasedIndexImpl.initIndexStorage(FileBasedIndexImpl.java:387)
	at com.intellij.util.indexing.FileBasedIndexImpl.registerIndexer(FileBasedIndexImpl.java:351)
	at com.intellij.util.indexing.FileBasedIndexImpl.access$5300(FileBasedIndexImpl.java:102)
	at com.intellij.util.indexing.FileBasedIndexImpl$FileIndexDataInitialization.lambda$new$0(FileBasedIndexImpl.java:2317)
	at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.executeNestedInitializationTask(IndexInfrastructure.java:211)
	at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.runParallelNestedInitializationTasks(IndexInfrastructure.java:201)
	at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.call(IndexInfrastructure.java:165)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:210)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-01-09 16:57:55,167 [   6189]   INFO - ij.psi.stubs.StubUpdatingIndex - Following new file types will be indexed:Kotlin,Go,KJSM,JAVA,CLASS,kotlin_builtins,SBT,XML,Scala,Properties,HTML,Groovy 
2017-01-09 16:57:55,394 [   6416]   INFO - pl$FileIndexDataInitialization - Initialization done:2693 
2017-01-09 16:57:55,494 [   6516]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.openapi.actionSystem.impl.ActionPreloader@7869a61a 
2017-01-09 16:57:55,993 [   7015]   INFO - ellij.project.impl.ProjectImpl - 183 project components initialized in 2107 ms 
2017-01-09 16:57:56,070 [   7092]   INFO - le.impl.ModuleManagerComponent - 1 module(s) loaded in 76 ms 
2017-01-09 16:57:56,888 [   7910]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 181ms; general responsiveness: ok; EDT responsiveness: ok 
2017-01-09 16:57:57,827 [   8849]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.ide.ui.search.SearchableOptionPreloader@c521fac 
2017-01-09 16:57:58,656 [   9678]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.codeInsight.completion.CompletionPreloader@635bb684 
2017-01-09 16:57:59,313 [  10335]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Project) or icon jar:file:/D:/IntelliJ%20IDEA%20Community%20Edition%202016.3/lib/icons.jar!/toolwindows/toolWindowProject.png 
2017-01-09 16:57:59,580 [  10602]   INFO - watcher.FwProjectChangeTracker - [tracking vfs changes] started 
2017-01-09 16:57:59,581 [  10603]   INFO - watcher.FwProjectChangeTracker - [tracking unsaved documents] started 
2017-01-09 16:57:59,582 [  10604]   INFO - watcher.FwProjectChangeTracker - [tracking vfs changes] start aborted: already running 
2017-01-09 16:57:59,582 [  10604]   INFO - watcher.FwProjectChangeTracker - [tracking unsaved documents] start aborted: already running 
2017-01-09 16:57:59,781 [  10803]   INFO - tartup.impl.StartupManagerImpl - D:/code/sample/test/.idea case-sensitivity: expected=false actual=false 
2017-01-09 16:58:00,595 [  11617]   INFO - tor.impl.FileEditorManagerImpl - Project opening took 6980 ms 
2017-01-09 16:58:03,080 [  14102]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 6190ms; general responsiveness: ok; EDT responsiveness: 2/6 sluggish, 1/6 very slow 
2017-01-09 16:58:03,089 [  14111]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update started: 47695 files to update 
2017-01-09 16:58:04,191 [  15213]   INFO - exImpl$StubIndexInitialization - Initialization done:8796 
2017-01-09 16:58:28,530 [  39552]   INFO - .diagnostic.PerformanceWatcher - Unindexed files update took 25441ms; general responsiveness: ok; EDT responsiveness: ok 
2017-01-09 16:58:29,808 [  40830]   INFO - CompilerWorkspaceConfiguration - Available processors: 4 
`


above logs are recorded when IDEA restarted after installing go-lang-plugin.

**Comment by yyrr001** [comment]
no more logs are recorded when I trie to set go SDK even it informed me of this error
