### ISSUE TITLE
EditorCopy: com.intellij.psi.PsiInvalidElementAccessException

### ISSUE THREAD

**Issue by hoha** [go-lang-plugin-org/go-lang-idea-plugin#2899]
- Plugin version (or commit hash):
- IDE name and version: Gogland 171.4694
- Java version: JetBrains s.r.o. 1.8.0_112
- OS name and version: Mac OS X

- What are you trying to do?

EditorCopy

- What would you expect to happen?

- What happens?

Details are unavailable since this issue is extracted from an automatic report

~~~~
In file: file:///Users/kakilangit/Go/src/gitlab.ruma.co.id/itdev/arisanlogic/cmd/arisanlogic/main.go

com.intellij.psi.PsiInvalidElementAccessException: Element: class com.goide.psi.impl.GoTypeSpecImpl; no psi for file stub GoFileStub, invalidation reason=onContentReload
	at com.intellij.psi.impl.source.SubstrateRef$StubRef.reportError(SubstrateRef.java:156)
	at com.intellij.psi.impl.source.SubstrateRef$StubRef.getContainingFile(SubstrateRef.java:148)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:275)
	at com.goide.psi.impl.GoStubbedElementImpl.getContainingFile(GoStubbedElementImpl.java:79)
	at com.goide.psi.impl.GoStubbedElementImpl.getContainingFile(GoStubbedElementImpl.java:32)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:133)
	at com.intellij.psi.PsiInvalidElementAccessException.getPsiInvalidationTrace(PsiInvalidElementAccessException.java:110)
	at com.intellij.psi.PsiInvalidElementAccessException.<init>(PsiInvalidElementAccessException.java:77)
	at com.intellij.psi.impl.source.SubstrateRef$StubRef.reportError(SubstrateRef.java:156)
	at com.intellij.psi.impl.source.SubstrateRef$StubRef.getContainingFile(SubstrateRef.java:148)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:275)
	at com.goide.psi.impl.GoStubbedElementImpl.getContainingFile(GoStubbedElementImpl.java:79)
	at com.goide.psi.impl.GoStubbedElementImpl.getContainingFile(GoStubbedElementImpl.java:32)
	at com.goide.psi.impl.GoPsiImplUtil.builtin(GoPsiImplUtil.java:87)
	at com.goide.psi.impl.GoNamedElementImpl.isPublic(GoNamedElementImpl.java:75)
	at com.goide.psi.impl.GoTypeReference.processNamedElements(GoTypeReference.java:182)
	at com.goide.psi.impl.GoTypeReference.processFileEntities(GoTypeReference.java:174)
	at com.goide.psi.impl.GoReferenceBase.processDirectory(GoReferenceBase.java:82)
	at com.goide.psi.impl.GoTypeReference.processQualifierExpression(GoTypeReference.java:112)
	at com.goide.psi.impl.GoTypeReference.processResolveVariants(GoTypeReference.java:92)
	at com.goide.psi.impl.GoTypeReference.resolveInner(GoTypeReference.java:60)
	at com.goide.psi.impl.GoTypeReference.lambda$static$0(GoTypeReference.java:54)
	at com.intellij.psi.impl.source.resolve.ResolveCache$PolyVariantResolver.resolve(ResolveCache.java:56)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:140)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:163)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:155)
	at com.goide.psi.impl.GoTypeReference.multiResolve(GoTypeReference.java:73)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:46)
	at com.goide.psi.GoReferenceExpressionBase.resolve(GoReferenceExpressionBase.java:37)
	at com.goide.psi.impl.GoPsiImplUtil.resolve(GoPsiImplUtil.java:727)
	at com.goide.psi.impl.GoTypeImpl.resolve(GoTypeImpl.java:55)
	at com.goide.psi.impl.GoNamedElementImpl.findSiblingType(GoNamedElementImpl.java:147)
	at com.goide.psi.impl.GoPsiImplUtil.getGoTypeInner(GoPsiImplUtil.java:370)
	at com.goide.psi.impl.GoParamDefinitionImpl.getGoTypeInner(GoParamDefinitionImpl.java:47)
	at com.goide.psi.impl.GoNamedElementImpl.lambda$getGoType$0(GoNamedElementImpl.java:132)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:141)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:137)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:127)
	at com.goide.psi.impl.GoNamedElementImpl.getGoType(GoNamedElementImpl.java:130)
	at com.goide.psi.impl.GoTypeUtil.getTypesAndIsVariadicFromParameters(GoTypeUtil.java:786)
	at com.goide.psi.impl.GoLightType$LightFunctionType.calcSignature(GoLightType.java:165)
	at com.goide.psi.impl.GoLightType$LightFunctionType.<init>(GoLightType.java:157)
	at com.goide.psi.impl.GoPsiImplUtil.getGoTypeInner(GoPsiImplUtil.java:1211)
	at com.goide.psi.impl.GoFunctionOrMethodDeclarationImpl.getGoTypeInner(GoFunctionOrMethodDeclarationImpl.java:41)
	at com.goide.psi.impl.GoNamedElementImpl.getGoType(GoNamedElementImpl.java:129)
	at com.goide.psi.impl.GoPsiImplUtil.typeOrParameterType(GoPsiImplUtil.java:717)
	at com.goide.psi.impl.GoPsiImplUtil.getGoTypeInner(GoPsiImplUtil.java:597)
	at com.goide.psi.impl.GoPsiImplUtil.unwrapParType(GoPsiImplUtil.java:431)
	at com.goide.psi.impl.GoPsiImplUtil.lambda$getGoType$3(GoPsiImplUtil.java:438)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.goide.psi.impl.GoPsiImplUtil.getGoType(GoPsiImplUtil.java:437)
	at com.goide.psi.impl.GoExpressionImpl.getGoType(GoExpressionImpl.java:32)
	at com.goide.psi.impl.GoPsiImplUtil.getGoTypeInner(GoPsiImplUtil.java:582)
	at com.goide.psi.impl.GoPsiImplUtil.unwrapParType(GoPsiImplUtil.java:431)
	at com.goide.psi.impl.GoPsiImplUtil.lambda$null$2(GoPsiImplUtil.java:440)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:141)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:137)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:127)
	at com.goide.psi.impl.GoPsiImplUtil.lambda$getGoType$3(GoPsiImplUtil.java:439)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.goide.psi.impl.GoPsiImplUtil.getGoType(GoPsiImplUtil.java:437)
	at com.goide.psi.impl.GoExpressionImpl.getGoType(GoExpressionImpl.java:32)
	at com.goide.inspections.GoInspectionUtil.getExpressionResultCount(GoInspectionUtil.java:41)
	at com.goide.highlighting.GoAnnotator$MyGoVisitor.visitCallExpr(GoAnnotator.java:154)
	at com.goide.psi.impl.GoCallExprImpl.accept(GoCallExprImpl.java:20)
	at com.goide.psi.impl.GoCallExprImpl.accept(GoCallExprImpl.java:24)
	at com.goide.highlighting.GoAnnotator.annotate(GoAnnotator.java:70)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:368)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:307)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:327)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:238)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

~~~~

**Comment by dlsniper** [comment]
Hi, I've opened the issue on the issue tracker for Gogland: https://youtrack.jetbrains.com/issue/GO-4218 Please follow the issue there. Thank you.

**Comment by ignatov** [comment]
@hoha could you please send /Users/kakilangit/Go/src/gitlab.ruma.co.id/itdev/arisanlogic/cmd/arisanlogic/main.go to my email for reproducing?
