### ISSUE TITLE
plugin throws exception on load

### ISSUE THREAD

**Issue by luck02** [go-lang-plugin-org/go-lang-idea-plugin#359]
Hi, I got the plugin from: https://www.dropbox.com/sh/kzcmavr2cmqqdqw/j8wjp8SdNH

I'm using IntelliJ 13 133.286 on WIndows 7

This could definitely be a result of my setting up the project, also I got the plugin link above from another trouble report as I just wanted a recent compiled jar to experiment with.

Looks like code autocompletion works for things in the base library but my dependencies (go get 'x') aren't showing up in autocomplete.

If there's a newer build to experiment with I'd happily check it out.

Thanks allot, looking forward to the new plugin version.

```
null
java.lang.NullPointerException
    at ro.redeul.google.go.lang.psi.impl.types.GoPsiTypeNameImpl.isIdentical(GoPsiTypeNameImpl.java:120)
    at ro.redeul.google.go.util.GoUtil.CompairTypes(GoUtil.java:235)
    at ro.redeul.google.go.inspection.FunctionCallInspection.checkParametersExp(FunctionCallInspection.java:189)
    at ro.redeul.google.go.inspection.FunctionCallInspection.checkFunctionTypeArguments(FunctionCallInspection.java:239)
    at ro.redeul.google.go.inspection.FunctionCallInspection.checkFunctionCallArguments(FunctionCallInspection.java:302)
    at ro.redeul.google.go.inspection.FunctionCallInspection.access$000(FunctionCallInspection.java:28)
    at ro.redeul.google.go.inspection.FunctionCallInspection$1.visitCallOrConvExpression(FunctionCallInspection.java:36)
    at ro.redeul.google.go.lang.psi.impl.expressions.primary.GoCallOrConvExpressionImpl.accept(GoCallOrConvExpressionImpl.java:78)
    at ro.redeul.google.go.lang.psi.impl.GoPsiElementBase.acceptChildren(GoPsiElementBase.java:61)
    at ro.redeul.google.go.lang.psi.visitors.GoRecursiveElementVisitor.visitElement(GoRecursiveElementVisitor.java:14)
    at ro.redeul.google.go.lang.psi.visitors.GoElementVisitor.visitReturnStatement(GoElementVisitor.java:175)
    at ro.redeul.google.go.lang.psi.impl.statements.GoReturnStatementImpl.accept(GoReturnStatementImpl.java:28)
    at ro.redeul.google.go.lang.psi.impl.GoPsiElementBase.acceptChildren(GoPsiElementBase.java:61)
    at ro.redeul.google.go.lang.psi.visitors.GoRecursiveElementVisitor.visitElement(GoRecursiveElementVisitor.java:14)
    at ro.redeul.google.go.lang.psi.impl.GoPsiElementBase.accept(GoPsiElementBase.java:48)
    at ro.redeul.google.go.lang.psi.impl.GoPsiElementBase.acceptChildren(GoPsiElementBase.java:61)
    at ro.redeul.google.go.lang.psi.visitors.GoRecursiveElementVisitor.visitElement(GoRecursiveElementVisitor.java:14)
    at ro.redeul.google.go.lang.psi.visitors.GoElementVisitor.visitMethodDeclaration(GoElementVisitor.java:59)
    at ro.redeul.google.go.lang.psi.impl.toplevel.GoMethodDeclarationImpl.accept(GoMethodDeclarationImpl.java:28)
    at ro.redeul.google.go.lang.psi.impl.GoFileImpl.acceptChildren(GoFileImpl.java:205)
    at ro.redeul.google.go.lang.psi.visitors.GoRecursiveElementVisitor.visitElement(GoRecursiveElementVisitor.java:14)
    at ro.redeul.google.go.lang.psi.visitors.GoElementVisitor.visitFile(GoElementVisitor.java:39)
    at ro.redeul.google.go.inspection.FunctionCallInspection.doCheckFile(FunctionCallInspection.java:31)
    at ro.redeul.google.go.inspection.AbstractWholeGoFileInspection.checkFile(AbstractWholeGoFileInspection.java:23)
    at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:144)
    at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
    at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:74)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$5.process(LocalInspectionsPass.java:382)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$5.process(LocalInspectionsPass.java:377)
    at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:119)
    at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:42)
    at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:82)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
    at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:91)
    at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:103)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:79)
    at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

```

**Comment by godolatry** [comment]
I had the same problem.  I've created a small app using another IDE and put it onto github (https://github.com/godolatry/films).  I imported it into IDEA and the IDE couldn't see my imported libraries (gorp etc), even though my Windows GOPATH environment variable includes the correct directory - gocode in my home directory.    I opened the module's settings (using F4) and set the SDK.  Under the same tab, the classpath list included gocode/src in my home directory, which it appears to have figured out from the GOPATH.  The Sourcepath was empty.  I added the gocode src directory to that, rebuilt the module and then everything compiled.

By the way, shouldn't the Classpath entry be gocode/pkg rather than gocode/src?  I'm guessing that it should be the directory containing the .a files rather than the src files.

For what it's worth: here is my environment:

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\simon>echo %GOPATH%
C:\Users\simon\gocode;c:\Users\simon\goprojects

C:\Users\simon>go env
set GOARCH=amd64
set GOBIN=
set GOCHAR=6
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\simon\gocode;c:\Users\simon\goprojects
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1


My project is outside the GOPATH as advised in this thread - it's in c:\intellij.workspace.
