### ISSUE TITLE
Null pointer Intellij 13 (3)

### ISSUE THREAD

**Issue by gertcuykens** [go-lang-plugin-org/go-lang-idea-plugin#513]
can not reproduce sorry

```java
null
java.lang.NullPointerException
	at ro.redeul.google.go.util.GoUtil.CompairTypes(GoUtil.java:300)
	at ro.redeul.google.go.inspection.FunctionCallInspection.checkParametersExp(FunctionCallInspection.java:172)
	at ro.redeul.google.go.inspection.FunctionCallInspection.checkFunctionTypeArguments(FunctionCallInspection.java:286)
	at ro.redeul.google.go.inspection.FunctionCallInspection.checkFunctionCallArguments(FunctionCallInspection.java:347)
	at ro.redeul.google.go.inspection.FunctionCallInspection.access$000(FunctionCallInspection.java:33)
	at ro.redeul.google.go.inspection.FunctionCallInspection$1.visitCallOrConvExpression(FunctionCallInspection.java:41)
	at ro.redeul.google.go.lang.psi.impl.expressions.primary.GoCallOrConvExpressionImpl.accept(GoCallOrConvExpressionImpl.java:78)
	at ro.redeul.google.go.lang.psi.impl.GoPsiElementBase.acceptChildren(GoPsiElementBase.java:61)
	at ro.redeul.google.go.lang.psi.visitors.GoRecursiveElementVisitor.visitElement(GoRecursiveElementVisitor.java:14)
	at ro.redeul.google.go.lang.psi.visitors.GoElementVisitor.visitShortVarDeclaration(GoElementVisitor.java:144)
	at ro.redeul.google.go.lang.psi.impl.statements.GoShortVarDeclarationImpl.accept(GoShortVarDeclarationImpl.java:34)
	at ro.redeul.google.go.lang.psi.impl.GoPsiElementBase.acceptChildren(GoPsiElementBase.java:61)
	at ro.redeul.google.go.lang.psi.visitors.GoRecursiveElementVisitor.visitElement(GoRecursiveElementVisitor.java:14)
	at ro.redeul.google.go.lang.psi.visitors.GoElementVisitor.visitIfStatement(GoElementVisitor.java:160)
	at ro.redeul.google.go.lang.psi.impl.statements.GoIfStatementImpl.accept(GoIfStatementImpl.java:65)
	at ro.redeul.google.go.lang.psi.impl.GoPsiElementBase.acceptChildren(GoPsiElementBase.java:61)
	at ro.redeul.google.go.lang.psi.visitors.GoRecursiveElementVisitor.visitElement(GoRecursiveElementVisitor.java:14)
	at ro.redeul.google.go.lang.psi.impl.GoPsiElementBase.accept(GoPsiElementBase.java:48)
	at ro.redeul.google.go.lang.psi.impl.GoPsiElementBase.acceptChildren(GoPsiElementBase.java:61)
	at ro.redeul.google.go.lang.psi.visitors.GoRecursiveElementVisitor.visitElement(GoRecursiveElementVisitor.java:14)
	at ro.redeul.google.go.lang.psi.visitors.GoElementVisitor.visitMethodDeclaration(GoElementVisitor.java:60)
	at ro.redeul.google.go.lang.psi.impl.toplevel.GoMethodDeclarationImpl.accept(GoMethodDeclarationImpl.java:28)
	at ro.redeul.google.go.lang.psi.impl.GoFileImpl.acceptChildren(GoFileImpl.java:205)
	at ro.redeul.google.go.lang.psi.visitors.GoRecursiveElementVisitor.visitElement(GoRecursiveElementVisitor.java:14)
	at ro.redeul.google.go.lang.psi.visitors.GoElementVisitor.visitFile(GoElementVisitor.java:40)
	at ro.redeul.google.go.inspection.FunctionCallInspection.doCheckFile(FunctionCallInspection.java:36)
	at ro.redeul.google.go.inspection.AbstractWholeGoFileInspection.checkFile(AbstractWholeGoFileInspection.java:23)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:144)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:74)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:358)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$000(LocalInspectionsPass.java:75)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$3.process(LocalInspectionsPass.java:327)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$3.process(LocalInspectionsPass.java:324)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:119)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:42)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:82)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:91)
	at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:103)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:79)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

**Comment by dlsniper** [comment]
This shouldn't happen anymore under 1.0
