### ISSUE TITLE
Formatting model exception while parsing incomplete declaration

### ISSUE THREAD

**Issue by m0sth8** [go-lang-plugin-org/go-lang-idea-plugin#607]
While parsing this code
```golang
package main

import "bytes"

func main() {
	var (
		body [] 
	)
	bytes.NewBuffer(body)
}
```
Plugin raises an Exception:
```
com.intellij.psi.impl.source.tree.PsiErrorElementImpl cannot be cast to ro.redeul.google.go.lang.psi.GoPsiElement: com.intellij.psi.impl.source.tree.PsiErrorElementImpl cannot be cast to ro.redeul.google.go.lang.psi.GoPsiElement
java.lang.ClassCastException: com.intellij.psi.impl.source.tree.PsiErrorElementImpl cannot be cast to ro.redeul.google.go.lang.psi.GoPsiElement
	at ro.redeul.google.go.util.GoUtil.ResolveTypeOfVarDecl(GoUtil.java:632)
	at ro.redeul.google.go.util.GoUtil.ResolveTypeOfVarDecl(GoUtil.java:639)
	at ro.redeul.google.go.util.GoTypeInspectUtil.checkParametersExp(GoTypeInspectUtil.java:124)
	at ro.redeul.google.go.util.GoTypeInspectUtil.checkFunctionTypeArguments(GoTypeInspectUtil.java:239)
	at ro.redeul.google.go.inspection.FunctionCallInspection.checkFunctionCallArguments(FunctionCallInspection.java:272)
	at ro.redeul.google.go.inspection.FunctionCallInspection.access$000(FunctionCallInspection.java:36)
	at ro.redeul.google.go.inspection.FunctionCallInspection$1.visitCallOrConvExpression(FunctionCallInspection.java:44)
	at ro.redeul.google.go.lang.psi.impl.expressions.primary.GoCallOrConvExpressionImpl.accept(GoCallOrConvExpressionImpl.java:78)
	at ro.redeul.google.go.lang.psi.impl.GoPsiElementBase.acceptChildren(GoPsiElementBase.java:61)
	at ro.redeul.google.go.lang.psi.visitors.GoRecursiveElementVisitor.visitElement(GoRecursiveElementVisitor.java:14)
	at ro.redeul.google.go.lang.psi.impl.GoPsiElementBase.accept(GoPsiElementBase.java:48)
	at ro.redeul.google.go.lang.psi.impl.GoPsiElementBase.acceptChildren(GoPsiElementBase.java:61)
	at ro.redeul.google.go.lang.psi.visitors.GoRecursiveElementVisitor.visitElement(GoRecursiveElementVisitor.java:14)
	at ro.redeul.google.go.lang.psi.visitors.GoElementVisitor.visitCallOrConvExpression(GoElementVisitor.java:184)
	at ro.redeul.google.go.inspection.FunctionCallInspection$1.visitCallOrConvExpression(FunctionCallInspection.java:42)
	at ro.redeul.google.go.lang.psi.impl.expressions.primary.GoCallOrConvExpressionImpl.accept(GoCallOrConvExpressionImpl.java:78)
	at ro.redeul.google.go.lang.psi.impl.GoPsiElementBase.acceptChildren(GoPsiElementBase.java:61)
	at ro.redeul.google.go.lang.psi.visitors.GoRecursiveElementVisitor.visitElement(GoRecursiveElementVisitor.java:14)
	at ro.redeul.google.go.lang.psi.impl.GoPsiElementBase.accept(GoPsiElementBase.java:48)
	at ro.redeul.google.go.lang.psi.impl.GoPsiElementBase.acceptChildren(GoPsiElementBase.java:61)
	at ro.redeul.google.go.lang.psi.visitors.GoRecursiveElementVisitor.visitElement(GoRecursiveElementVisitor.java:14)
	at ro.redeul.google.go.lang.psi.visitors.GoElementVisitor.visitAssignment(GoElementVisitor.java:240)
	at ro.redeul.google.go.lang.psi.impl.statements.GoAssignmentStatementImpl.accept(GoAssignmentStatementImpl.java:70)
	at ro.redeul.google.go.lang.psi.impl.GoPsiElementBase.acceptChildren(GoPsiElementBase.java:61)
	at ro.redeul.google.go.lang.psi.visitors.GoRecursiveElementVisitor.visitElement(GoRecursiveElementVisitor.java:14)
	at ro.redeul.google.go.lang.psi.impl.GoPsiElementBase.accept(GoPsiElementBase.java:48)
	at ro.redeul.google.go.lang.psi.impl.GoPsiElementBase.acceptChildren(GoPsiElementBase.java:61)
	at ro.redeul.google.go.lang.psi.visitors.GoRecursiveElementVisitor.visitElement(GoRecursiveElementVisitor.java:14)
	at ro.redeul.google.go.lang.psi.visitors.GoElementVisitor.visitFunctionDeclaration(GoElementVisitor.java:64)
	at ro.redeul.google.go.lang.psi.impl.toplevel.GoFunctionDeclarationImpl.accept(GoFunctionDeclarationImpl.java:148)
	at ro.redeul.google.go.lang.psi.impl.GoFileImpl.acceptChildren(GoFileImpl.java:219)
	at ro.redeul.google.go.lang.psi.visitors.GoRecursiveElementVisitor.visitElement(GoRecursiveElementVisitor.java:14)
	at ro.redeul.google.go.lang.psi.visitors.GoElementVisitor.visitFile(GoElementVisitor.java:40)
	at ro.redeul.google.go.inspection.FunctionCallInspection.doCheckFile(FunctionCallInspection.java:39)
	at ro.redeul.google.go.inspection.AbstractWholeGoFileInspection.checkFile(AbstractWholeGoFileInspection.java:23)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:144)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:74)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$5.process(LocalInspectionsPass.java:382)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$5.process(LocalInspectionsPass.java:377)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:119)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:42)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:82)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1150)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:91)
	at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:103)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:79)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

**Comment by dlsniper** [comment]
The issues with the formatter will be addressed in 1.0 as that has its own problems
