### ISSUE TITLE
NPE when trying to edit debug configuration or project structure

### ISSUE THREAD

**Issue by polyfractal** [go-lang-plugin-org/go-lang-idea-plugin#629]
Preface: it is entirely possible I am doing something wrong, or have the plugin configured incorrectly. :)

I cloned and built the most recent master (at commit 54cb7de58996633ac9f0d54025859f9365e44c25), generated the .jar file and loaded it into IntelliJ.  The plugin appears to load fine, go code is syntax highlighted, etc.  I can place breakpoints as well.

But when I attempt to debug...nothing happens.  I tried to edit the debug config, because I assumed there were some settings that needed to be changed, and it threw an NPE.

I am using IntelliJ 13.0.2 Ultimate Edition on Mac OSX Mavericks

Edit:  Looks to be related to #622 ?

```
[ 119430]  ERROR - llij.ide.plugins.PluginManager - null 
java.lang.NullPointerException
	at ro.redeul.google.go.runner.ui.GoRunConfigurationEditorForm.<init>(GoRunConfigurationEditorForm.java:73)
	at ro.redeul.google.go.runner.GoApplicationConfiguration.getConfigurationEditor(GoApplicationConfiguration.java:101)
	at com.intellij.execution.impl.ConfigurationSettingsEditor.<init>(ConfigurationSettingsEditor.java:168)
	at com.intellij.execution.impl.ConfigurationSettingsEditorWrapper.<init>(ConfigurationSettingsEditorWrapper.java:59)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.<init>(SingleConfigurationConfigurable.java:63)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.editSettings(SingleConfigurationConfigurable.java:97)
	at com.intellij.execution.impl.RunConfigurable.a(RunConfigurable.java:378)
	at com.intellij.execution.impl.RunConfigurable.access$500(RunConfigurable.java:76)
	at com.intellij.execution.impl.RunConfigurable$4.valueChanged(RunConfigurable.java:267)
	at javax.swing.JTree.fireValueChanged(JTree.java:2820)
	at javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3191)
	at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:629)
	at com.intellij.ui.treeStructure.Tree$MySelectionModel.fireValueChanged(Tree.java:651)
	at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1078)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:287)
	at javax.swing.JTree.setSelectionPaths(JTree.java:1611)
	at javax.swing.JTree.setSelectionRows(JTree.java:1684)
	at javax.swing.JTree.setSelectionRow(JTree.java:1659)
	at com.intellij.util.ui.tree.TreeUtil$1.run(TreeUtil.java:519)
	at com.intellij.util.ui.tree.TreeUtil.showAndSelect(TreeUtil.java:570)
	at com.intellij.util.ui.tree.TreeUtil.showRowCentered(TreeUtil.java:462)
	at com.intellij.util.ui.tree.TreeUtil.showRowCentered(TreeUtil.java:453)
	at com.intellij.util.ui.tree.TreeUtil.showRowCentred(TreeUtil.java:448)
	at com.intellij.util.ui.tree.TreeUtil.selectPath(TreeUtil.java:379)
	at com.intellij.util.ui.tree.TreeUtil.selectInTree(TreeUtil.java:829)
	at com.intellij.util.ui.tree.TreeUtil.selectInTree(TreeUtil.java:817)
	at com.intellij.execution.impl.RunConfigurable$6.run(RunConfigurable.java:324)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:205)
	at java.awt.Dialog$1.run(Dialog.java:1049)
	at java.awt.Dialog$3.run(Dialog.java:1101)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Dialog.show(Dialog.java:1099)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:786)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:462)
	at com.intellij.openapi.ui.DialogWrapper.showAndGetOk(DialogWrapper.java:1543)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1511)
	at com.intellij.execution.actions.EditRunConfigurationsAction.actionPerformed(EditRunConfigurationsAction.java:47)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:162)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:261)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:916)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:231)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:104)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2351)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:291)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:389)
	at com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:178)
	at java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:372)
	at java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:340)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:343)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:331)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:720)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:690)
	at java.awt.EventQueue$3.run(EventQueue.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
[ 119432]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 13.0.2  Build #IU-133.696 
[ 119432]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.6.0_65 
[ 119432]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM 
[ 119432]  ERROR - llij.ide.plugins.PluginManager - Vendor: Apple Inc. 
[ 119432]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X 
[ 119432]  ERROR - llij.ide.plugins.PluginManager - Last Action: editRunConfigurations 
```

Similar occurrence when trying to edit the project structure.  Nothing appears to happen in the UI, but an NPE is thrown behind the scenes:

```
[ 362680]  ERROR - llij.ide.plugins.PluginManager - null 
java.lang.NullPointerException
	at java.awt.Container.addImpl(Container.java:1044)
	at java.awt.Container.add(Container.java:926)
	at com.intellij.openapi.projectRoots.ui.SdkEditor.f(SdkEditor.java:366)
	at com.intellij.openapi.projectRoots.ui.SdkEditor.reset(SdkEditor.java:243)
	at com.intellij.openapi.projectRoots.ui.SdkEditor.a(SdkEditor.java:109)
	at com.intellij.openapi.projectRoots.ui.SdkEditor.<init>(SdkEditor.java:92)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.JdkConfigurable.createSdkEditor(JdkConfigurable.java:57)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.JdkConfigurable.<init>(JdkConfigurable.java:51)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.JdkListConfigurable.loadTree(JdkListConfigurable.java:128)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.BaseStructureConfigurable.reset(BaseStructureConfigurable.java:268)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.JdkListConfigurable.reset(JdkListConfigurable.java:168)
	at com.intellij.openapi.roots.ui.configuration.ProjectStructureConfigurable.reset(ProjectStructureConfigurable.java:348)
	at com.intellij.openapi.options.ex.SingleConfigurableEditor.<init>(SingleConfigurableEditor.java:66)
	at com.intellij.openapi.options.ex.SingleConfigurableEditor.<init>(SingleConfigurableEditor.java:89)
	at com.intellij.openapi.options.ex.SingleConfigurableEditor.<init>(SingleConfigurableEditor.java:104)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.a(ShowSettingsUtilImpl.java:253)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.editConfigurable(ShowSettingsUtilImpl.java:228)
	at com.intellij.ide.actions.ShowStructureSettingsAction.actionPerformed(ShowStructureSettingsAction.java:36)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:162)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:261)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:916)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:231)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:104)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2351)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:291)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:389)
	at com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:178)
	at java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:372)
	at java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:340)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:343)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:331)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:720)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:690)
	at java.awt.EventQueue$3.run(EventQueue.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
[ 362681]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 13.0.2  Build #IU-133.696 
[ 362681]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.6.0_65 
[ 362681]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM 
[ 362681]  ERROR - llij.ide.plugins.PluginManager - Vendor: Apple Inc. 
[ 362681]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X 
[ 362681]  ERROR - llij.ide.plugins.PluginManager - Last Action: ShowProjectStructureSettings 
```

Let me know if I can provide any more information!

EDIT 2:  Various debug info as requested by the "reporting issues" page:

Go SDK Environment:
```
Project dir -> /Users/tongz/Documents/go/logstash-forwarder
GO_GOROOT_PATH -> /usr/local/Cellar/go/1.2/libexec
GO_BIN_PATH -> /usr/local/Cellar/go/1.2/libexec/bin/go
GO_GOPATH_PATH -> /Users/tongz/Documents/go
TARGET_OS -> Darwin
TARGET_ARCH -> _amd64
VERSION_MAJOR -> go1.2 darwin/amd64
VERSION_MINOR -> 
Extended Go Env -> 
OLDPWD=/Applications/IntelliJ IDEA 13.app/Contents
TERM=ansi
SHELL=/bin/bash
TMPDIR=/var/folders/py/pczw6mkd6hbbbklfqj85lm700000gn/T/
SHLVL=1
TERM_PROGRAM_VERSION=326
SECURITYSESSIONID=186a4
__CF_USER_TEXT_ENCODING=0x1F5:0:0
TERM_PROGRAM=Apple_Terminal
PATH=/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/go/bin:/Users/tongz/Dropbox/go/bin:/usr/local/Cellar/go/1.2/libexec/bin:/Users/tongz/Dropbox/go/bin:/Users/tongz/Documents/go/logstash-forwarder/bin
GOROOT=/usr/local/Cellar/go/1.2/libexec
GOPATH=/Users/tongz/Dropbox/go:/Users/tongz/Documents/go/logstash-forwarder
USER=tongz
PWD=/Applications/IntelliJ IDEA 13.app/Contents/MacOS
TERM_SESSION_ID=F7F49EFE-2CB5-4DDE-88F8-454FD94449BE
HOME=/Users/tongz
LOGNAME=tongz
PHPBREW_ROOT=/Users/tongz/.phpbrew
Apple_PubSub_Socket_Render=/tmp/launch-eAksXK/Render
PHPBREW_HOME=/Users/tongz/.phpbrew
_=./idea
__CHECKFIX1436934=1
SSH_AUTH_SOCK=/tmp/launch-9rTyBE/Listeners
LANG=en_US.UTF-8
```

Go env:
```
Project dir -> /Users/tongz/Documents/go/logstash-forwarder
/usr/local/Cellar/go/1.2/libexec/bin/go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/tongz/Dropbox/go:/Users/tongz/Documents/go/logstash-forwarder"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.2/libexec/pkg/tool/darwin_amd64"
TERM="dumb"
CC="clang"
GOGCCFLAGS="-g -O2 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

System env:
```
Project dir -> /Users/tongz/Documents/go/logstash-forwarder
TERM=ansi
OLDPWD=/Applications/IntelliJ IDEA 13.app/Contents
SHELL=/bin/bash
TMPDIR=/var/folders/py/pczw6mkd6hbbbklfqj85lm700000gn/T/
TERM_PROGRAM_VERSION=326
SHLVL=1
SECURITYSESSIONID=186a4
TERM_PROGRAM=Apple_Terminal
__CF_USER_TEXT_ENCODING=0x1F5:0:0
PATH=/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/go/bin:/Users/tongz/Dropbox/go/bin
GOPATH=/Users/tongz/Dropbox/go
USER=tongz
PWD=/Applications/IntelliJ IDEA 13.app/Contents/MacOS
TERM_SESSION_ID=F7F49EFE-2CB5-4DDE-88F8-454FD94449BE
HOME=/Users/tongz
PHPBREW_ROOT=/Users/tongz/.phpbrew
LOGNAME=tongz
Apple_PubSub_Socket_Render=/tmp/launch-eAksXK/Render
PHPBREW_HOME=/Users/tongz/.phpbrew
_=./idea
SSH_AUTH_SOCK=/tmp/launch-9rTyBE/Listeners
__CHECKFIX1436934=1
LANG=en_US.UTF-8
```

**Comment by dlsniper** [comment]
Not applicable anymore.
