### ISSUE TITLE
Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation

### ISSUE THREAD

**Issue by nkev** [go-lang-plugin-org/go-lang-idea-plugin#742]
Got the error below, running a simple test app. The app is also below. Mac OSX 10.9.4, Go 1.3, current plugin build (last week actually). Once I cleared the error and ran the app, it worked fine from then on. Here's the app:

	package main

	import "fmt"

	type vertex struct{ x, y int }

	func pointers() {

	vertexOrignal := vertex{1, 2}

	//This is going to make a copy of the original.
	vertexCopy := vertexOrignal
	vertexCopy.x = 3
	vertexCopy.y = 4

	//vertexOrignal.x, vertexOrignal.y will remain unchange
	//since it mutated the copy //This will assign a pointer to vertexReference instead of
	//copying the value.
	vertexReference := &vertexOrignal

	vertexOrignal.x = 3
	vertexOrignal.y = 4
	//vertexOrignal.x, vertexOrignal.y will change
	//since it mutated the the pointer.

	fmt.Printf("%#v\n", *vertexReference)

	}

	func main() {
		pointers()
	}

Error is as follows:
```
Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:853)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:802)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:786)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:244)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:232)
	at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:75)
	at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:94)
	at com.intellij.psi.stubs.StubIndexImpl.get(StubIndexImpl.java:221)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:142)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:132)
	at com.intellij.psi.stubs.StubIndex.safeGet(StubIndex.java:124)
	at ro.redeul.google.go.lang.stubs.GoNamesCache.getFilesByPackageName(GoNamesCache.java:182)
	at ro.redeul.google.go.ide.structureview.GoStructureViewElement$TypeInfo.getAllSamePackageFiles(GoStructureViewElement.java:422)
	at ro.redeul.google.go.ide.structureview.GoStructureViewElement$TypeInfo.getMethods(GoStructureViewElement.java:456)
	at ro.redeul.google.go.ide.structureview.GoStructureViewElement$StructInfo.getMembers(GoStructureViewElement.java:486)
	at ro.redeul.google.go.ide.structureview.GoStructureViewElement$TypeInfo.getChildren(GoStructureViewElement.java:383)
	at ro.redeul.google.go.ide.structureview.GoStructureViewElement.<init>(GoStructureViewElement.java:48)
	at ro.redeul.google.go.ide.structureview.GoStructureViewElement.<init>(GoStructureViewElement.java:43)
	at ro.redeul.google.go.ide.structureview.GoStructureViewElement$FileInfo.getChildren(GoStructureViewElement.java:171)
	at ro.redeul.google.go.ide.structureview.GoStructureViewElement.<init>(GoStructureViewElement.java:48)
	at ro.redeul.google.go.ide.structureview.GoStructureViewElement.<init>(GoStructureViewElement.java:43)
	at ro.redeul.google.go.ide.structureview.GoStructureView$1$1.getRoot(GoStructureView.java:24)
	at com.intellij.ide.impl.StructureViewWrapperImpl.a(StructureViewWrapperImpl.java:192)
	at com.intellij.ide.impl.StructureViewWrapperImpl.a(StructureViewWrapperImpl.java:163)
	at com.intellij.ide.impl.StructureViewWrapperImpl.access$100(StructureViewWrapperImpl.java:69)
	at com.intellij.ide.impl.StructureViewWrapperImpl$1.run(StructureViewWrapperImpl.java:105)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.a(ActionManagerImpl.java:1376)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.a(ActionManagerImpl.java:1365)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.actionPerformed(ActionManagerImpl.java:1352)
	at javax.swing.Timer.fireActionPerformed(Timer.java:291)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:221)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by dlsniper** [comment]
This shouldn't happen in 1.0 anymore.
