### ISSUE TITLE
I can not enter a new line after a case of switch in a rare case.

### ISSUE THREAD

**Issue by bronze1man** [go-lang-plugin-org/go-lang-idea-plugin#815]
```
package IdeaTest

type t1 string

func (m *t1) abc() (err error) {
	Diamond:=0
	switch Diamond{
	case 1:
	}
	Diamond + = Diamond
	return
}
```
I can not enter a new line after `case 1:`
![image](https://cloud.githubusercontent.com/assets/1107541/4627469/8af9422e-538b-11e4-8ceb-89e6f429b8ba.png)

```
null
java.lang.NullPointerException
	at ro.redeul.google.go.formatter.blocks.GoBinaryExpressionBlock.<init>(GoBinaryExpressionBlock.java:71)
	at ro.redeul.google.go.formatter.blocks.GoBlockGenerator.generateBlock(GoBlockGenerator.java:57)
	at ro.redeul.google.go.formatter.blocks.GoBlockGenerator.generateBlock(GoBlockGenerator.java:42)
	at ro.redeul.google.go.formatter.blocks.GoBlock.buildChildren(GoBlock.java:154)
	at ro.redeul.google.go.formatter.blocks.GoBlock.getSubBlocks(GoBlock.java:132)
	at com.intellij.formatting.InitialInfoBuilder.buildFrom(InitialInfoBuilder.java:176)
	at com.intellij.formatting.InitialInfoBuilder.doIteration(InitialInfoBuilder.java:235)
	at com.intellij.formatting.InitialInfoBuilder.iteration(InitialInfoBuilder.java:109)
	at com.intellij.formatting.FormatProcessor$WrapBlocksState.doIteration(FormatProcessor.java:1313)
	at com.intellij.formatting.FormatProcessor$State.iteration(FormatProcessor.java:1246)
	at com.intellij.formatting.FormatProcessor.iteration(FormatProcessor.java:244)
	at com.intellij.formatting.FormatterImpl.buildProcessorAndWrapBlocks(FormatterImpl.java:434)
	at com.intellij.formatting.FormatterImpl.adjustLineIndent(FormatterImpl.java:371)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$5.doPerform(CodeStyleManagerImpl.java:358)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$5.doPerform(CodeStyleManagerImpl.java:355)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerRunnable.perform(CodeStyleManagerRunnable.java:112)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.doAdjustLineIndentByOffset(CodeStyleManagerImpl.java:355)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.access$500(CodeStyleManagerImpl.java:60)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$3.compute(CodeStyleManagerImpl.java:318)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$3.compute(CodeStyleManagerImpl.java:315)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:116)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.adjustLineIndent(CodeStyleManagerImpl.java:315)
	at com.intellij.codeInsight.editorActions.EnterHandler$DoEnterAction.run(EnterHandler.java:423)
	at com.intellij.codeInsight.editorActions.EnterHandler.executeWriteActionInner(EnterHandler.java:170)
	at com.intellij.codeInsight.editorActions.EnterHandler.access$000(EnterHandler.java:53)
	at com.intellij.codeInsight.editorActions.EnterHandler$1.run(EnterHandler.java:75)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect$2.compute(PostprocessReformattingAspect.java:107)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:116)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:104)
	at com.intellij.codeInsight.editorActions.EnterHandler.executeWriteAction(EnterHandler.java:72)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:64)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:984)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:47)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:125)
	at com.intellij.codeInsight.template.impl.editorActions.EnterHandler.executeWriteAction(EnterHandler.java:54)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:64)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:984)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:47)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$1.perform(EditorActionHandler.java:120)
	at com.intellij.openapi.editor.impl.CaretModelImpl$3.run(CaretModelImpl.java:355)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:426)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:349)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:117)
	at com.intellij.openapi.editor.actionSystem.EditorAction$1.run(EditorAction.java:83)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:124)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:94)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:68)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:463)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:493)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by dlsniper** [comment]
The formatter in 1.0 has different problems than the 0.9.x and it's likely that 0.9.16 won't be released before 1.0
