### ISSUE TITLE
NPE in ro.redeul.google.go.ide.ui.GoModuleWizardStepPackageConfig

### ISSUE THREAD

**Issue by growler** [go-lang-plugin-org/go-lang-idea-plugin#930]
Got NPE with a fresh build of plugin:

    java.lang.NullPointerException
    	at ro.redeul.google.go.ide.ui.GoModuleWizardStepPackageConfig.<init>(GoModuleWizardStepPackageConfig.java:29)
    	at ro.redeul.google.go.ide.GoModuleType.createWizardSteps(GoModuleType.java:82)

The failed line is

            radioNewPackage.addActionListener(new ActionListener() {

Seems like radioNewPackage is not initialized

**Comment by dlsniper** [comment]
This shouldn't be a problem on 1.0 anymore.
