### ISSUE TITLE
GoLiteralIdentifierImpl parent is null

### ISSUE THREAD

**Issue by bronze1man** [go-lang-plugin-org/go-lang-idea-plugin#948]
here is the code I just edited:
```
package kmgHttp

import (
	"bufio"
	"bytes"
	"io/ioutil"
	"net/http"
	"net/http/httputil"
	"io"
)

func NewRequestFromByte(r []byte) (req *http.Request, err error) {
	return http.ReadRequest(bufio.NewReader(bytes.NewReader(r)))
}

//sometimes it is hard to remember how to get response from bytes ...
func NewResponseFromBytes(r []byte) (resp *http.Response, err error) {
	return http.ReadResponse(bufio.NewReader(bytes.NewBuffer(r)), &http.Request{})
}

//sometimes it is hard to remember how to dump response to bytes
func DumpResponseToBytes(resp *http.Response) (b []byte, err error) {
	return httputil.DumpResponse(resp, true)
}

func ResponseReadAllBody(resp *http.Response) (b []byte, err error) {
	defer resp.Body.Close()
	return ioutil.ReadAll(resp.Body)
}

func UrlGetContent(url string) (b []byte, err error) {
	resp, err := http.Get(url)
	if err != nil {
		return
	}
	return ResponseReadAllBody(resp)
}

func HeaderToString(header http.Header) (s string) {
	buf := &bytes.Buffer{}
	header.Write(buf)
	return string(buf.Bytes())
}

//把request转换成[]byte,并且使body可以被再次读取
func MustRequestToStringCanRead(req *http.Request)(s string){
	oldBody:=req.Body
	defer oldBody.Close()
	body,err:=ioutil.ReadAll(req.Body)
	if err!=nil{
		panic(err)
	}
	req.Body=ioutil.NopCloser(&bytes.NewReader(body))
	buf:=&bytes.Buffer{}
	req.Write(buf)
	req.Body=ioutil.NopCloser(&bytes.NewReader(body))
	return string(buf.Bytes())
}

func MustRequestFromString(reqString string)(req *http.Request){
	http.Read
}
```

```
Element: class ro.redeul.google.go.lang.psi.impl.expressions.literals.GoLiteralIdentifierImpl because: parent is null
invalidated at: see attachment
com.intellij.psi.PsiInvalidElementAccessException: Element: class ro.redeul.google.go.lang.psi.impl.expressions.literals.GoLiteralIdentifierImpl because: parent is null
invalidated at: see attachment
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getManager(ASTDelegatePsiElement.java:63)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getManager(ASTDelegatePsiElement.java:49)
	at com.intellij.psi.impl.PsiElementBase.getProject(PsiElementBase.java:214)
	at ro.redeul.google.go.lang.packages.GoPackages.getPackageFor(GoPackages.java:140)
	at ro.redeul.google.go.lang.psi.resolve.Reference.canSee(Reference.java:64)
	at ro.redeul.google.go.lang.psi.resolve.ReferenceSolvingVisitor.checkIdentifiers(ReferenceSolvingVisitor.java:24)
	at ro.redeul.google.go.lang.psi.resolve.refs.VarOrConstSolver$1.visitShortVarDeclaration(VarOrConstSolver.java:43)
	at ro.redeul.google.go.lang.psi.impl.statements.GoShortVarDeclarationImpl.accept(GoShortVarDeclarationImpl.java:39)
	at ro.redeul.google.go.lang.psi.impl.GoPsiElementBase.accept(GoPsiElementBase.java:54)
	at ro.redeul.google.go.lang.psi.resolve.VisitingReferenceSolver.execute(VisitingReferenceSolver.java:24)
	at ro.redeul.google.go.lang.psi.impl.statements.GoShortVarDeclarationImpl.processDeclarations(GoShortVarDeclarationImpl.java:49)
	at ro.redeul.google.go.lang.psi.impl.statements.GoBlockStatementImpl.processDeclarations(GoBlockStatementImpl.java:33)
	at ro.redeul.google.go.lang.psi.utils.GoPsiScopesUtil.treeWalkUp(GoPsiScopesUtil.java:58)
	at ro.redeul.google.go.lang.psi.resolve.refs.VarOrConstReference.walkSolver(VarOrConstReference.java:38)
	at ro.redeul.google.go.lang.psi.resolve.refs.VarOrConstReference.walkSolver(VarOrConstReference.java:13)
	at ro.redeul.google.go.lang.psi.resolve.DefaultReferenceSolver.resolve(DefaultReferenceSolver.java:55)
	at ro.redeul.google.go.lang.psi.resolve.DefaultReferenceSolver.resolve(DefaultReferenceSolver.java:14)
	at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:144)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:141)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:215)
	at ro.redeul.google.go.lang.psi.resolve.DefaultReferenceSolver.resolveFromCache(DefaultReferenceSolver.java:80)
	at ro.redeul.google.go.lang.psi.resolve.DefaultReferenceSolver.resolve(DefaultReferenceSolver.java:22)
	at ro.redeul.google.go.lang.psi.resolve.ReferenceWithSolver.resolve(ReferenceWithSolver.java:32)
	at ro.redeul.google.go.lang.psi.utils.GoPsiUtils.resolveSafely(GoPsiUtils.java:94)
	at ro.redeul.google.go.annotator.GoAnnotator.processLiteralIdentifier(GoAnnotator.java:207)
	at ro.redeul.google.go.annotator.GoAnnotator.visitLiteralExpression(GoAnnotator.java:182)
	at ro.redeul.google.go.lang.psi.impl.expressions.primary.GoLiteralExpressionImpl.accept(GoLiteralExpressionImpl.java:57)
	at ro.redeul.google.go.annotator.GoAnnotator.annotate(GoAnnotator.java:64)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:160)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:103)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$5.run(GeneralHighlightingPass.java:313)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:399)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$300(GeneralHighlightingPass.java:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$6.run(GeneralHighlightingPass.java:405)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:87)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:402)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$300(GeneralHighlightingPass.java:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$6.run(GeneralHighlightingPass.java:405)
	at com.intellij.codeInsight.daemon.impl.RefCountHolder.analyze(RefCountHolder.java:321)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:175)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:402)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:390)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:230)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1143)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.registerIndicatorAndRun(ProgressManagerImpl.java:281)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)



com.intellij.psi.PsiInvalidElementAccessException: Element: class ro.redeul.google.go.lang.psi.impl.expressions.literals.GoLiteralIdentifierImpl because: parent is null
invalidated at: see attachment
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getManager(ASTDelegatePsiElement.java:63)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getManager(ASTDelegatePsiElement.java:49)
	at com.intellij.psi.impl.PsiElementBase.getProject(PsiElementBase.java:214)
	at ro.redeul.google.go.lang.packages.GoPackages.getPackageFor(GoPackages.java:140)
	at ro.redeul.google.go.lang.psi.resolve.Reference.canSee(Reference.java:64)
	at ro.redeul.google.go.lang.psi.resolve.ReferenceSolvingVisitor.checkIdentifiers(ReferenceSolvingVisitor.java:24)
	at ro.redeul.google.go.lang.psi.resolve.refs.VarOrConstSolver$1.visitShortVarDeclaration(VarOrConstSolver.java:43)
	at ro.redeul.google.go.lang.psi.impl.statements.GoShortVarDeclarationImpl.accept(GoShortVarDeclarationImpl.java:39)
	at ro.redeul.google.go.lang.psi.impl.GoPsiElementBase.accept(GoPsiElementBase.java:54)
	at ro.redeul.google.go.lang.psi.resolve.VisitingReferenceSolver.execute(VisitingReferenceSolver.java:24)
	at ro.redeul.google.go.lang.psi.impl.statements.GoShortVarDeclarationImpl.processDeclarations(GoShortVarDeclarationImpl.java:49)
	at ro.redeul.google.go.lang.psi.impl.statements.GoBlockStatementImpl.processDeclarations(GoBlockStatementImpl.java:33)
	at ro.redeul.google.go.lang.psi.utils.GoPsiScopesUtil.treeWalkUp(GoPsiScopesUtil.java:58)
	at ro.redeul.google.go.lang.psi.resolve.refs.VarOrConstReference.walkSolver(VarOrConstReference.java:38)
	at ro.redeul.google.go.lang.psi.resolve.refs.VarOrConstReference.walkSolver(VarOrConstReference.java:13)
	at ro.redeul.google.go.lang.psi.resolve.DefaultReferenceSolver.resolve(DefaultReferenceSolver.java:55)
	at ro.redeul.google.go.lang.psi.resolve.DefaultReferenceSolver.resolve(DefaultReferenceSolver.java:14)
	at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:144)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:141)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:215)
	at ro.redeul.google.go.lang.psi.resolve.DefaultReferenceSolver.resolveFromCache(DefaultReferenceSolver.java:80)
	at ro.redeul.google.go.lang.psi.resolve.DefaultReferenceSolver.resolve(DefaultReferenceSolver.java:22)
	at ro.redeul.google.go.lang.psi.resolve.ReferenceWithSolver.resolve(ReferenceWithSolver.java:32)
	at ro.redeul.google.go.util.GoUtil.ResolveReferece(GoUtil.java:296)
	at ro.redeul.google.go.lang.psi.impl.expressions.primary.GoLiteralExpressionImpl$LiteralTypeCalculator.fun(GoLiteralExpressionImpl.java:127)
	at ro.redeul.google.go.lang.psi.impl.expressions.primary.GoLiteralExpressionImpl$LiteralTypeCalculator.fun(GoLiteralExpressionImpl.java:66)
	at ro.redeul.google.go.services.GoPsiManager.getType(GoPsiManager.java:71)
	at ro.redeul.google.go.lang.psi.impl.expressions.primary.GoLiteralExpressionImpl.getType(GoLiteralExpressionImpl.java:234)
	at ro.redeul.google.go.lang.psi.impl.expressions.literals.GoLiteralIdentifierImpl.defineReferences(GoLiteralIdentifierImpl.java:256)
	at ro.redeul.google.go.lang.psi.impl.GoPsiElementBase.getReferences(GoPsiElementBase.java:83)
	at org.intellij.plugins.intelliLang.references.InjectedReferencesContributor.getInjectedReferences(InjectedReferencesContributor.java:55)
	at org.intellij.plugins.intelliLang.references.InjectedReferencesInspection$1.visitElement(InjectedReferencesInspection.java:38)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:80)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:289)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$000(LocalInspectionsPass.java:75)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:258)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:255)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1143)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.registerIndicatorAndRun(ProgressManagerImpl.java:281)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.registerIndicatorAndRun(ProgressManagerImpl.java:278)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

**Comment by dlsniper** [comment]
This shouldn't happen anymore in 1.0
